Update km terms check :chm-64
scbd/absch.cbd.int pull request #1030
Opened 2024-02-13 10:19 UTC by tahmeedshah

### General description
create a filter 'escape', If our selector contains special characters like periods (.) or colons (:), we need to escape them properly.
update km-terms-check

### Designs
_Link to the related design prototypes (if applicable)_

### Testing instructions
_Provide minimal instructions on how to test this PR._

* Apart from the added feature / bug fix, check overall performance, styling...

## Checklist before merging
* [ ]  Branch name / PR includes the related Jira ticket Id.
* [ ]  Tests to check core implementation / bug fix added.
* [ ]  All checks in Continuous Integration workflow pass.
* [ ]  Feature functionally tested by reviewer(s).
* [ ]  Code reviewed by reviewer(s).
* [ ]  Documentation updated (README, CHANGELOG...) (if required)

2024-02-16 14:43 UTC, sbilodeau requested changes

2024-02-16 14:43 UTC, sbilodeau commented on app/components/scbd-angularjs-services/filters/scbd-filters.js
> +  });
escape is very generic name. cna we use more mesaningful?

eg: `escapeHtmlAttribuetId`

I would suggest to reverse the regex with only allowed char and replace all other ones with underscore using 

```jsvascript 
/[^-_:.a-z0-9]/ig
```
The fisrt `^` insinde `[ ]` mean NOT. therefore the above regex mean: matche everything except follwing allowed chars: `-` `_` `:` `.` `a` to `z` and `0` to `9`

base on W3C: ID and Name attribute value valid char are: 
> ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").
https://www.w3.org/TR/html4/types.html#:~:text=ID%20and%20NAME%20tokens%20must,tokens%20defined%20by%20other%20attributes.

therefore I would suggest follwing code:
```suggestion
  app.filter('escapeHtmlAttribuetId', function() {
    return function(value) {
      return value.replace(/[^-_:.a-z0-9]/gi, '_');
    };
  });
```

2024-02-16 15:50 UTC, tahmeedshah commented on app/components/scbd-angularjs-services/filters/scbd-filters.js
> +  });
done as suggested

2024-02-16 22:00 UTC, blaisefonseca commented on app/components/scbd-angularjs-services/filters/scbd-filters.js
> +    return function(value) {
can you extract it to the service folder as discussed in scrum

2024-02-19 15:41 UTC, blaisefonseca approved these changes

2024-02-19 15:42 UTC, merged