migrate relevant articles to Vue3
scbd/absch.cbd.int pull request #1073
Opened 2024-03-21 17:45 UTC by tahmeedshah

### General description
_Please write a description. If the PR is hard to understand, provide a quick explanation of the code._

### Designs
_Link to the related design prototypes (if applicable)_

### Testing instructions
_Provide minimal instructions on how to test this PR._

* Apart from the added feature / bug fix, check overall performance, styling...

## Checklist before merging
* [ ]  Branch name / PR includes the related Jira ticket Id.
* [ ]  Tests to check core implementation / bug fix added.
* [ ]  All checks in Continuous Integration workflow pass.
* [ ]  Feature functionally tested by reviewer(s).
* [ ]  Code reviewed by reviewer(s).
* [ ]  Documentation updated (README, CHANGELOG...) (if required)

2024-03-28 13:45 UTC, blaisefonseca commented on app/components/kb/relevant-articles.vue
> +    const { tag, type, sort } = defineProps({
destructing the props will loose the reactivity, use 
```suggestion
    const props = defineProps({
```

2024-03-28 13:47 UTC, blaisefonseca commented on app/components/kb/relevant-articles.vue
> +    };
move it to services

2024-03-28 15:10 UTC, tahmeedshah commented on app/components/kb/relevant-articles.vue
> +    const { tag, type, sort } = defineProps({
updated as suggested.

2024-03-28 15:10 UTC, tahmeedshah commented on app/components/kb/relevant-articles.vue
> +    };
updated as suggested.

2024-04-02 20:48 UTC, sbilodeau requested changes

2024-04-02 20:48 UTC, sbilodeau commented on app/components/kb/relevant-articles.vue
> +        ag.push({"$match":{"$and":[{"adminTags":encodeURIComponent(props.tag)}]}});
i know it comes from the old file but why `props.tag` are encoded?

2024-04-02 20:48 UTC, sbilodeau commented on app/components/kb/relevant-articles.vue
> +    const { t } = useI18n({ messages });
```suggestion
    const { t, locale } = useI18n({ messages });
```

2024-04-02 20:48 UTC, sbilodeau commented on app/components/kb/relevant-articles.vue
>                  <a class="link-dark fs-6" :href="`${articleUrl(article)}`">{{lstring(article.title, $locale)}}</a>
I think `$locale` is legacy and should come from the ```const { locale } = useI18n()```
```suggestion
                <a class="link-dark fs-6" :href="`${articleUrl(article)}`">{{lstring(article.title, locale)}}</a>
```

2024-04-03 10:39 UTC, tahmeedshah commented on app/components/kb/relevant-articles.vue
> +    const { t } = useI18n({ messages });
done.

2024-04-03 10:40 UTC, tahmeedshah commented on app/components/kb/relevant-articles.vue
> +        ag.push({"$match":{"$and":[{"adminTags":encodeURIComponent(props.tag)}]}});
yes, we can remove it.

2024-04-03 10:41 UTC, tahmeedshah commented on app/components/kb/relevant-articles.vue
>                  <a class="link-dark fs-6" :href="`${articleUrl(article)}`">{{lstring(article.title, $locale)}}</a>
done.

2024-04-05 15:14 UTC, blaisefonseca approved these changes

2024-04-05 16:08 UTC, sbilodeau approved these changes

2024-04-05 16:08 UTC, merged