Migrate Model component to Vue3
scbd/absch.cbd.int pull request #1078
Opened 2024-03-26 10:13 UTC by tahmeedshah

### General description
_Please write a description. If the PR is hard to understand, provide a quick explanation of the code._

### Designs
_Link to the related design prototypes (if applicable)_

### Testing instructions
_Provide minimal instructions on how to test this PR._

* Apart from the added feature / bug fix, check overall performance, styling...

## Checklist before merging
* [ ]  Branch name / PR includes the related Jira ticket Id.
* [ ]  Tests to check core implementation / bug fix added.
* [ ]  All checks in Continuous Integration workflow pass.
* [ ]  Feature functionally tested by reviewer(s).
* [ ]  Code reviewed by reviewer(s).
* [ ]  Documentation updated (README, CHANGELOG...) (if required)

2024-04-02 20:19 UTC, sbilodeau requested changes

2024-04-02 20:19 UTC, sbilodeau commented on app/components/common/modal.vue
> +    const modalRef = ref(null);
suggest to use shallowRef
https://github.com/vuejs/core/discussions/6894

2024-04-02 20:19 UTC, sbilodeau commented on app/components/common/modal.vue
> +    const titleRef = ref('')
not used 
```suggestion
```

2024-04-02 20:19 UTC, sbilodeau commented on app/components/common/modal.vue
> +        titleRef.value = title;
useless simply use title directly
```suggestion
```

2024-04-03 08:54 UTC, tahmeedshah commented on app/components/common/modal.vue
> +    const modalRef = ref(null);
done.

2024-04-05 15:19 UTC, blaisefonseca commented on app/components/common/modal.vue
> +  </script> -->
can you delete this part
```suggestion
```

2024-04-05 15:20 UTC, blaisefonseca commented on app/components/common/modal.vue
> +        modal = Modal.getInstance(modalRef.value);
move this line to onMounted so that you have to do this only once.

2024-04-05 16:47 UTC, tahmeedshah commented on app/components/common/modal.vue
> +  </script> -->
removed.

2024-04-15 22:17 UTC, blaisefonseca commented
Small comments

2024-04-16 16:11 UTC, tahmeedshah commented on app/components/common/modal.vue
> +    defineExpose({show, close})
allowing parent or sibling components to directly call these functions.

2024-04-16 17:59 UTC, blaisefonseca approved these changes

2024-04-16 18:00 UTC, sbilodeau approved these changes

2024-04-16 18:00 UTC, merged