Migrate Export component to Vue3
scbd/absch.cbd.int pull request #1079
Opened 2024-03-26 17:08 UTC by tahmeedshah

### General description
_Please write a description. If the PR is hard to understand, provide a quick explanation of the code._

### Designs
_Link to the related design prototypes (if applicable)_

### Testing instructions
_Provide minimal instructions on how to test this PR._

* Apart from the added feature / bug fix, check overall performance, styling...

## Checklist before merging
* [ ]  Branch name / PR includes the related Jira ticket Id.
* [ ]  Tests to check core implementation / bug fix added.
* [ ]  All checks in Continuous Integration workflow pass.
* [ ]  Feature functionally tested by reviewer(s).
* [ ]  Code reviewed by reviewer(s).
* [ ]  Documentation updated (README, CHANGELOG...) (if required)

2024-04-02 20:15 UTC, sbilodeau requested changes

2024-04-02 20:15 UTC, sbilodeau commented on app/components/common/export.vue
> +                                                            <a v-if="row.rec_uniqueIdentifier" rel="noopener" target="_blank" :href="`database/${(row.rec_uniqueIdentifier).toUpperCase()}`">
I think it is missing `encodeURIComponent`
```suggestion
                                                            <a v-if="row.rec_uniqueIdentifier" rel="noopener" target="_blank" :href="`database/${encodeURIComponent((row.rec_uniqueIdentifier).toUpperCase())}`">
```

2024-04-02 20:15 UTC, sbilodeau commented on app/components/common/export.vue
> +                        console.log('getDownloadRecords', typeof getDownloadRecords) // type of getDownloadRecords object, it should be function.
can drop this line
```suggestion
```

2024-04-02 20:15 UTC, sbilodeau commented on app/components/common/export.vue
> +    const exportModal = ref(null);
i think for dom `refs` (from line 7) it's better to use `shallowRef` as the reactivity will be only on the reference and not on the dom elelment OR component

https://vuejs.org/api/reactivity-advanced.html#reactivity-api-advanced
```suggestion
    const exportModal = shallowRef(null);
```

2024-04-02 20:15 UTC, sbilodeau commented on app/views/search/directives/result-view-options.js
> +                    }
can you import from `angular-vue` or extract to the services folder?

2024-04-03 08:28 UTC, tahmeedshah commented on app/components/common/export.vue
> +                                                            <a v-if="row.rec_uniqueIdentifier" rel="noopener" target="_blank" :href="`database/${(row.rec_uniqueIdentifier).toUpperCase()}`">
added encodeURIComponent

2024-04-03 08:30 UTC, tahmeedshah commented on app/views/search/directives/result-view-options.js
> +                    }
moved safeApply to services/common.js

2024-04-05 15:23 UTC, blaisefonseca approved these changes

2024-04-05 20:06 UTC, sbilodeau approved these changes

2024-04-05 20:06 UTC, merged