remove 'LAB-' from the start of LAB name in LAB Registry
scbd/absch.cbd.int pull request #1081
Opened 2024-03-29 06:13 UTC by tahmeedshah

### General description
Removed the word ‘LAB’ in the second column in front of names. But leave it everywhere else.

### Designs
_Link to the related design prototypes (if applicable)_

### Testing instructions
_Provide minimal instructions on how to test this PR._

* Apart from the added feature / bug fix, check overall performance, styling...

## Checklist before merging
* [ ]  Branch name / PR includes the related Jira ticket Id.
* [ ]  Tests to check core implementation / bug fix added.
* [ ]  All checks in Continuous Integration workflow pass.
* [ ]  Feature functionally tested by reviewer(s).
* [ ]  Code reviewed by reviewer(s).
* [ ]  Documentation updated (README, CHANGELOG...) (if required)

2024-04-01 14:24 UTC, sbilodeau requested changes

2024-04-01 14:24 UTC, sbilodeau commented on app/views/reports/bch/registries/view-lab-registry.js
> +			}
@blaisefonseca will say that i'm always saying that but...
you can also use regular expresssion `/^LAB -/`. if the pattern match it will be replaced by empty string!
you can also have variant with variable number of spaces or invariant case eg:
``` javascript
/^LAB\s*-\s*/i
```
eg: https://regexr.com/7u9si

```suggestion
			return str.replace(/^LAB\s*-\s*/i, '');
```

2024-04-02 20:01 UTC, sbilodeau approved these changes

2024-04-12 14:41 UTC, blaisefonseca commented
This change is no longer required, closing the PR

2024-04-12 14:41 UTC, closed without merging