update post component
scbd/absch.cbd.int pull request #1213
Opened 2024-07-21 10:10 UTC by tahmeedshah

### General description
_Please write a description. If the PR is hard to understand, provide a quick explanation of the code._

### Designs
_Link to the related design prototypes (if applicable)_

### Testing instructions
_Provide minimal instructions on how to test this PR._

* Apart from the added feature / bug fix, check overall performance, styling...

## Checklist before merging
* [ ]  Branch name / PR includes the related Jira ticket Id.
* [ ]  Tests to check core implementation / bug fix added.
* [ ]  All checks in Continuous Integration workflow pass.
* [ ]  Feature functionally tested by reviewer(s).
* [ ]  Code reviewed by reviewer(s).
* [ ]  Documentation updated (README, CHANGELOG...) (if required)

2024-07-25 17:21 UTC, sbilodeau requested changes

2024-07-25 17:21 UTC, sbilodeau commented on app/components/forums/post.vue
> +                        <a v-if="showLinkToParent" :href="`#${post.parentId}`" @click="jumpToAnchor" :title="t('replyToId', { postId:post.parentId })"><i class="fa fa-arrow-up"></i></a>
```suggestion
                        <a v-if="showLinkToParent" :href="`#${post.parentId}`" @click="jumpToAnchor()" :title="t('replyToId', { postId:post.parentId })"><i class="fa fa-arrow-up"></i></a>
```

2024-07-25 17:21 UTC, sbilodeau commented on app/components/forums/post.vue
> +                        <button class="btn btn-light btn-sm" @click.prevent="toggleReplies" v-if="post.replies">
```suggestion
                        <button class="btn btn-light btn-sm" @click.prevent="toggleReplies()" v-if="post.replies">
```

2024-07-25 17:21 UTC, sbilodeau commented on app/components/forums/post.vue
> +                        <button type="button" class="btn btn-light btn-sm" @click.prevent="edit">
```suggestion
                        <button type="button" class="btn btn-light btn-sm" @click.prevent="edit()">
```

2024-07-25 17:21 UTC, sbilodeau commented on app/components/forums/post.vue
> +                            <li><a class="dropdown-item" href="#" @click.prevent="edit">
```suggestion
                            <li><a class="dropdown-item" href="#" @click.prevent="edit()">
```

2024-07-25 17:21 UTC, sbilodeau commented on app/components/forums/post.vue
> +                                <a class="dropdown-item" href="#" @click.prevent="togglePin">
```suggestion
                                <a class="dropdown-item" href="#" @click.prevent="togglePin()">
```

2024-07-25 17:21 UTC, sbilodeau commented on app/components/forums/post.vue
> +                                <a class="dropdown-item" href="#" @click.prevent="toggleClose">
```suggestion
                                <a class="dropdown-item" href="#" @click.prevent="toggleClose()">
```

2024-07-25 17:21 UTC, sbilodeau commented on app/components/forums/post.vue
> +                            <li v-if="canDelete && !post.replies"><a class="dropdown-item text-danger" href="#" @click.prevent="deletePost">
```suggestion
                            <li v-if="canDelete && !post.replies"><a class="dropdown-item text-danger" href="#" @click.prevent="deletePost()">
```

2024-07-25 17:21 UTC, sbilodeau commented on app/components/forums/post.vue
> +const route = useRoute().value;
doing `.value` make current route non reactive

2024-07-25 17:22 UTC, sbilodeau commented on app/components/forums/post.vue
> +                        <a v-if="showLinkToParent" :href="`#${post.parentId}`" @click="jumpToAnchor" :title="t('replyToId', { postId:post.parentId })"><i class="fa fa-arrow-up"></i></a>
preferably use callback with `()`. make it clear it's a call and control parapmeter passed to the function.

using `@click="jumpToAnchor"` passes the click `$event` to the function. while `@click="jumpToAnchor()"` passes nothing.

it's safer to prevent side-effects

2024-07-30 14:47 UTC, sbilodeau approved these changes

2024-07-30 15:35 UTC, blaisefonseca approved these changes

2024-07-30 16:07 UTC, merged