migrate thread-id component to vue3
scbd/absch.cbd.int pull request #1220
Opened 2024-07-23 09:24 UTC by tahmeedshah

### General description
_Please write a description. If the PR is hard to understand, provide a quick explanation of the code._

### Designs
_Link to the related design prototypes (if applicable)_

### Testing instructions
_Provide minimal instructions on how to test this PR._

* Apart from the added feature / bug fix, check overall performance, styling...

## Checklist before merging
* [ ]  Branch name / PR includes the related Jira ticket Id.
* [ ]  Tests to check core implementation / bug fix added.
* [ ]  All checks in Continuous Integration workflow pass.
* [ ]  Feature functionally tested by reviewer(s).
* [ ]  Code reviewed by reviewer(s).
* [ ]  Documentation updated (README, CHANGELOG...) (if required)

2024-07-25 17:14 UTC, sbilodeau approved these changes

2024-07-25 17:14 UTC, sbilodeau commented on app/views/portals/thread-id.vue
> +            <span v-if="replies  > 1"><i class="fa fa-comments"></i> {{ t('linkXReplies', { count: replies }) }} </span>
would have been nice to use plurarization `tc`

2024-07-25 17:14 UTC, sbilodeau commented on app/views/portals/thread-id.vue
> +        <post class="mb-2 border-top" v-for="reply in posts" :key="reply.postId" :post="reply" @refresh="load" />
preferable to use event with `()`
```suggestion
        <post class="mb-2 border-top" v-for="reply in posts" :key="reply.postId" :post="reply" @refresh="load()" />
```

2024-07-26 15:11 UTC, sbilodeau commented on app/views/portals/thread-id.vue
> +            <span v-if="replies  > 1"><i class="fa fa-comments"></i> {{ tc('linkXReplies', { count: replies }) }} </span>
theorartically it should use only one tranlsationKey no?
eg:
```html
            <span v-if="replies == 0"> {{ tc('linkXReplies', { count: replies }) }}</span>
            <span v-if="replies >= 1"><i class="fa fa-comment"></i> {{ tc('linkXReplies', { count: replies }) }} </span>
```
```json
{
  "linkXReplies": "No replies | One reply |  {count} replies" 
}
```

2024-07-30 14:46 UTC, sbilodeau requested changes

2024-07-30 14:46 UTC, sbilodeau commented on app/app-text/views/portals/forums.json
>     "linkOneReply": "One reply",
should delete the unused keys no?
```suggestion
```

2024-07-30 19:29 UTC, sbilodeau approved these changes

2024-07-31 12:42 UTC, sbilodeau requested changes

2024-07-31 12:42 UTC, sbilodeau commented on app/views/portals/thread-id.vue
> +            <span v-if="replies  > 1"><i class="fa fa-comments"></i> {{ t('linkXReplies', { count: replies }) }}</span>
can we make it on line with `v-if`? I think we can drop the `comment` vs `comments`.
or we keep it with `:class`
```suggestion
            <span>
                <i v-if="replies>0" class="fa" : class="{ 'fa-comment':replies==1, 'fa-comments':replies>1 }"></i>
                {{ t('linkXReplies', { count: replies }) }}
            </span>
```

2024-07-31 20:02 UTC, blaisefonseca approved these changes

2024-08-05 17:02 UTC, sbilodeau approved these changes

2024-08-05 17:02 UTC, merged