ABSCH/BCH - Improve search date picker CHM-246
scbd/absch.cbd.int pull request #1279
Opened 2024-12-02 11:34 UTC by tahmeedshah

### General description

create km-date-picker-range component
update date range in search directive

### Designs
_Link to the related design prototypes (if applicable)_

### Testing instructions
_Provide minimal instructions on how to test this PR._

* Apart from the added feature / bug fix, check overall performance, styling...

## Checklist before merging
* [ ]  Branch name / PR includes the related Jira ticket Id.
* [ ]  Tests to check core implementation / bug fix added.
* [ ]  All checks in Continuous Integration workflow pass.
* [ ]  Feature functionally tested by reviewer(s).
* [ ]  Code reviewed by reviewer(s).
* [ ]  Documentation updated (README, CHANGELOG...) (if required)

2024-12-03 19:00 UTC, sbilodeau commented on app/components/km/km-date-picker-range.vue
> +    });
why this onMounted there? there is no reason to default value to today. if need the parent user must set it. 
Moreover the value format must have been validated by the prop validator

2024-12-03 19:01 UTC, sbilodeau commented on app/views/search/search-directive.js
> +                        let dateQuery = dateVal.value.start + ' - ' + dateVal.value.end
used natural format for uend user eg: 3 Nov 2022

2024-12-04 13:29 UTC, tahmeedshah commented on app/components/km/km-date-picker-range.vue
> +        "Last 30 Days": [moment().subtract(29, "days"), moment()],
added .startOfDay()

2024-12-04 13:33 UTC, tahmeedshah commented on app/components/km/km-date-picker-range.vue
> +            errorMessage.value = "The end date cannot be earlier than the start date.";
text moved to translation file

2024-12-04 14:33 UTC, sbilodeau requested changes

2024-12-04 14:33 UTC, sbilodeau commented on app/components/km/km-date-picker-range.vue
> +    });
why you converted this to a props? 
date data format cannot be diffrent than YYYY-MM-DD

2024-12-04 14:33 UTC, sbilodeau commented on app/components/km/km-date-picker-range.vue
> +    });
you need validator that check the value to be valid:
`null` || `{ startDate, endDate }` with format

2024-12-04 14:33 UTC, sbilodeau commented on app/components/km/km-date-picker-range.vue
> +    }));
sorry the start of day is useless as we only take "date" portion. 
the data shoudl be date only not moment object

2024-12-04 14:33 UTC, sbilodeau commented on app/views/search/search-directive.js
> +                        const endDateText = moment(dateVal.value.end, dateFormat).format("DD MMM YYYY");
the `DD MMM YYYY` shoudl come from the global setting.

2024-12-04 14:33 UTC, sbilodeau commented on app/views/search/search-filters/date-filter.html
> +                    date-format="YYYY-MM-DD"
does not make send to specify the format. the data cannot be diffrent format for date. it an ISO standard

2024-12-11 17:52 UTC, sbilodeau requested changes

2024-12-11 17:52 UTC, sbilodeau commented on app/components/km/km-date-picker-range.vue
> +    const onFilterDateChange = inject("onFilterDateChange");
what is this used for?
I think you can do the thing with normal event
the start/end model one no?

2024-12-11 17:52 UTC, sbilodeau commented on app/components/km/km-date-picker-range.vue
> +      // },
why did you commented the validation?
missing allow `null`

2024-12-11 17:52 UTC, sbilodeau commented on app/components/km/km-date-picker-range.vue
> +    };
directly passe the start/end valud instead of the label

2024-12-11 17:52 UTC, sbilodeau commented on app/components/scbd-angularjs-controls/form-control-directives/km-date-range.js
> +            provide('onFilterDateChange', safeDelegate($scope, ()=>{
why this provider? this si wrong component pattern.
use model event instead: `@update:start="..."`  `@update:end="..."` if you need to handle a onchnage

2024-12-11 17:52 UTC, sbilodeau commented on app/services/datetime.js
> +}
reanme to formatDateISO

2024-12-11 17:52 UTC, sbilodeau commented on app/services/datetime.js
> +  return moment.utc(date).format(dateFormat); //  "19 Jan 2024";
why use of `utc`?
I think we shoudl excpect the date to be passed in client timezone
```suggestion
  return moment(date).format(dateFormat); //  "19 Jan 2024";
```

2024-12-11 17:52 UTC, sbilodeau commented on app/views/search/search-filters/date-filter.js
> +                    provide('onFilterDateChange', safeDelegate($scope, ()=>{
same as for https://github.com/scbd/absch.cbd.int/pull/1279/files#diff-6eab6520899cce9f24a15d9e1f812f5ef3da8d692da45c272abf783501a264b8R40

2024-12-12 20:50 UTC, sbilodeau approved these changes

2024-12-19 16:17 UTC, sbilodeau approved these changes

2024-12-19 19:26 UTC, merged