Update Solr queries for contain - chm-626
scbd/absch.cbd.int pull request #1299
Opened 2024-12-21 13:30 UTC by tahmeedshah

### General description
_Please write a description. If the PR is hard to understand, provide a quick explanation of the code._

### Designs
_Link to the related design prototypes (if applicable)_

### Testing instructions
_Provide minimal instructions on how to test this PR._

* Apart from the added feature / bug fix, check overall performance, styling...

## Checklist before merging
* [ ]  Branch name / PR includes the related Jira ticket Id.
* [ ]  Tests to check core implementation / bug fix added.
* [ ]  All checks in Continuous Integration workflow pass.
* [ ]  Feature functionally tested by reviewer(s).
* [ ]  Code reviewed by reviewer(s).
* [ ]  Documentation updated (README, CHANGELOG...) (if required)

2024-12-24 14:14 UTC, sbilodeau requested changes

2025-05-19 13:37 UTC, blaisefonseca commented on app/services/solr/queries.js
> +    return `(${wordQueries.join(` ${operator} `)})`; // &fl=${searchField}`;
the solr service has fucntion to build these and or queries, check them

2025-05-19 19:25 UTC, blaisefonseca approved these changes

2025-05-22 15:48 UTC, blaisefonseca approved these changes

2025-05-22 15:51 UTC, merged