bchn news feature added.
scbd/absch.cbd.int pull request #377
Opened 2020-10-01 12:59 UTC by tahmeedshah

New module bchn added.

Please disregard all the prev commits and branches

2020-10-01 13:43 UTC, blaisefonseca commented on app/views/forms/view/bch/view-biosafety-news.directive.js
> +		'components/scbd-angularjs-controls/form-control-directives/km-value-bool'
remove unsued reference to `'components/scbd-angularjs-controls/form-control-directives/km-value-bool'`

2020-10-01 13:45 UTC, blaisefonseca commented on app/views/search/search-filters/bch-left-menu-filters.json
> +		}
the title and newsText are string fields, thesaurus is a predifined list, there is no use for this filter, please remove

2020-10-01 13:45 UTC, blaisefonseca commented on app/views/search/search-filters/bch-left-menu-filters.json
> +		},
sub-filter not requried, can be deleted

2020-10-01 13:48 UTC, blaisefonseca commented on app/views/forms/view/bch/view-biosafety-news.directive.js
> +		restrict   : "EAC",
lets restrict directive to element and attributes only, remove C

2020-10-01 13:49 UTC, blaisefonseca commented on app/views/forms/view/bch/view-biosafety-news.directive.js
> +			}
this function is not used, please remove

2020-10-01 13:53 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-biosafety-news.directive.html
> +													filter="genericFilter" mapping="genericMapping" selectbox="true"
use startsWithFilter `filter="startsWithFilter"`

2020-10-01 13:56 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-biosafety-news.directive.html
> +												caption="BCH node address
the caption of the field is only `BCH node address`, remaing text is help text should be on next line
`<div class="help-info" > Help text here</div>`

2020-10-01 13:58 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-biosafety-news.directive.js
> +	'views/forms/edit/document-selector', "views/forms/view/bch/view-biosafety-news.directive"],
remove use used reference to thesaurusservice and document-selector

2020-10-01 13:58 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-biosafety-news.directive.js
> +	app.directive("editBiosafetyNews", ["$controller", "thesaurusService", function($controller, thesaurusService) {
remove theasuarusService refernce

2020-10-01 13:59 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-biosafety-news.directive.js
> +				$scope.commonNames = [{}];
remove used used scope variables

2020-10-01 14:00 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-biosafety-news.directive.js
> +                     delete document['government']
no governent field exists in the schema, please. remove

2020-10-01 14:00 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-biosafety-news.directive.js
> +                });
no use of this code, please remove

2020-10-01 14:07 UTC, blaisefonseca requested changes
please confirm, if the you were able to publish the record and view it in search result

2020-10-01 14:07 UTC, blaisefonseca commented on app/views/forms/edit/bch/edit-biosafety-news.js
> +define(['app', 'lodash', 'views/forms/edit/edit', './directives/edit-biosafety-news.directive'],
remove loadash reference

2020-10-01 14:07 UTC, blaisefonseca commented on app/views/forms/view/bch/view-biosafety-news.directive.html
> +		<div ng-show="document.country">
use ng-if instead of ng-show

2020-10-01 14:07 UTC, blaisefonseca commented on app/views/forms/view/bch/view-biosafety-news.directive.html
> +		<div ng-show="document.title">
use ng-if instead of ng-show

2020-10-01 14:07 UTC, blaisefonseca commented on app/views/forms/view/bch/view-biosafety-news.directive.html
> +		<div ng-show="document.nodeAddress">
use ng-if instead of ng-show

2020-10-01 14:07 UTC, blaisefonseca commented on app/views/forms/view/bch/view-biosafety-news.directive.html
> +		<div ng-show="document.newsText">
use ng-if instead of ng-show

2020-10-01 14:07 UTC, blaisefonseca commented on app/views/forms/view/bch/view-biosafety-news.directive.html
> +		<div ng-show="document.newsAbstract">
use ng-if instead of ng-show

2020-10-01 14:07 UTC, blaisefonseca commented on app/views/forms/view/bch/view-biosafety-news.directive.js
> +			hide	: "@"
remove unused hide

2020-10-01 14:07 UTC, blaisefonseca commented on app/views/forms/view/bch/view-biosafety-news.directive.js
> +			}
since the controller will be empty, it can be removed as well

2020-10-02 11:37 UTC, tahmeedshah commented on app/views/forms/edit/bch/directives/edit-biosafety-news.directive.js
> +                     delete document['government']
Government field seems generic in all request, I can't remove it the schema throws error.

0: {code: "Error.InvalidProperty", property: "government"}
code: "Error.InvalidProperty"
property: "government"

For now I keep it this way. I can remove it in future.

2020-10-02 13:57 UTC, blaisefonseca commented
Please make sure the changes are working and do not push changes without testing
1. Edit route is not working 
2. The record view is not working (from search, dashboard)

2020-10-02 14:02 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-biosafety-news.directive.js
> +                     delete document['government']
it maybe because u have old record which has government, just try a new record

2020-10-02 14:12 UTC, blaisefonseca requested changes

2020-10-02 14:12 UTC, blaisefonseca commented on app/views/forms/view/bch/view-biosafety-news.directive.html
> +			<div class="km-value">
no need for `<div class="km-value">` as the control km-value-ml takes care of it

2020-10-02 14:12 UTC, blaisefonseca commented on app/views/forms/view/bch/view-biosafety-news.directive.html
> +			<div class="km-value">
no need for `<div class="km-value">` as the control km-value-ml takes care of it

2020-10-02 14:12 UTC, blaisefonseca commented on app/views/forms/view/bch/view-biosafety-news.directive.html
> +			<div class="km-value">
no need for `<div class="km-value">` as the control km-value-ml takes care of it

2020-10-02 14:12 UTC, blaisefonseca commented on app/views/search/search-filters/bch-left-menu-filters.json
> +		}
country subfilter not required, please remove

2020-10-02 14:12 UTC, blaisefonseca commented on app/routes/bch.js
> +               whenAsync('/register/BCHN/new',                 {templateUrl: 'views/forms/edit/bch/edit-biosafety-news.html', label:'New', param:'true', resolveController: true,documentType :'biosafe
missing edit route, see the section below for edit routes

2020-10-02 14:38 UTC, blaisefonseca commented
Please can you update the offline format links in `/app/app-data/bch/offline-formats.json` for biosafetyNews
```
ar : http://bch.cbd.int/resources/common%20formats/referencerecord_05_bchnews_ar.doc?download
en : http://bch.cbd.int/resources/common%20formats/referencerecord_05_bchnews_en.doc?download
es : http://bch.cbd.int/resources/common%20formats/referencerecord_05_bchnews_es.doc?download
fr : http://bch.cbd.int/resources/common%20formats/referencerecord_05_bchnews_fr.doc?download
ru : http://bch.cbd.int/resources/common%20formats/referencerecord_05_bchnews_ru.doc?download
zh : http://bch.cbd.int/resources/common%20formats/referencerecord_05_bchnews_zh.doc?download
```

2020-10-05 17:37 UTC, blaisefonseca commented
below fields are missing in edit screen
```
relevantInformation 
relevantDocuments  
```

2020-10-05 17:50 UTC, blaisefonseca requested changes

2020-10-05 17:50 UTC, blaisefonseca commented on app/routes/bch.js
> +               whenAsync('/register/BCHN/:identifier/edit',           {templateUrl: 'views/forms/edit/bch/edit-biosafety-news.html',                label:'Edit',  param:'true', resolveController: tru
please make sure `{templateUrl:` is aliged with rest of the lines

2020-10-05 17:50 UTC, blaisefonseca commented on app/views/forms/view/bch/view-biosafety-news.directive.html
> +			<label>Node Address</label>
lowercase A in Address, correct label is `BCH node address`

2020-10-05 17:50 UTC, blaisefonseca commented on app/views/forms/view/bch/view-biosafety-news.directive.html
> +			<label>News Text</label>
lowercase T in Text

2020-10-06 14:28 UTC, tahmeedshah commented
use km-link-list control, refer the BCH node address field
km-link-list control is used in view directive and if we use it in the edit directive then unable to see the add link button

2020-10-06 15:41 UTC, blaisefonseca approved these changes

2020-10-06 15:46 UTC, randyhoulahan approved these changes

2020-10-06 15:49 UTC, merged