Bch country profile
scbd/absch.cbd.int pull request #384
Opened 2020-10-15 10:14 UTC by tahmeedshah

This pull request contains all files, changes for country profile including

1. Edit
2. View
3. Listing
4. Country profile card on countries page

2020-10-15 19:38 UTC, blaisefonseca requested changes

2020-10-15 19:38 UTC, blaisefonseca commented on app/views/countries/country-profile.html
> -
I don't see any changes in this section still it was commited?

2020-10-15 19:38 UTC, blaisefonseca commented on app/views/countries/country-profile.html
> -</div>
I don't see any changes in this section still it was commited?

2020-10-15 19:38 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-country-profile.directive.html
> +												<div class="help-block">Please use this field to provide any other relevant information that may not have been addressed elsewhere in the record.</div>
Please update the text as u have done in DEVDESK-417

2020-10-16 15:35 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-country-profile.directive.js
> +				$scope.validateCountryProfileExists = function(identifier){
no need to be on scope, make this function local
`$scope.checkRecordAlreadyExists,
$scope.validateCountryProfileExists`

2020-10-16 15:36 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-country-profile.directive.js
> +							const identifier = result.data.response.docs[0].identifier_s;
const will not work in browser, chrome will handle but older browser will not

2020-10-16 15:37 UTC, blaisefonseca commented on app/views/forms/edit/bch/edit-country-profile.js
>  	function($scope,  $controller,  IStorage, $routeParams, ngDialog,searchService) {
`function($scope,  $controller,  IStorage, $routeParams, ngDialog,searchService) {` unused params

2020-10-17 07:34 UTC, tahmeedshah commented on app/views/forms/edit/bch/edit-country-profile.js
>  	function($scope,  $controller,  IStorage, $routeParams, ngDialog,searchService) {
IStorage removed.

2020-10-17 07:34 UTC, tahmeedshah commented on app/views/forms/edit/bch/directives/edit-country-profile.directive.js
> +							const identifier = result.data.response.docs[0].identifier_s;
const to var

2020-10-17 07:34 UTC, tahmeedshah commented on app/views/forms/edit/bch/directives/edit-country-profile.directive.js
> +				$scope.validateCountryProfileExists = function(identifier){
code refactor - local functions

2020-10-19 14:19 UTC, randyhoulahan approved these changes

2020-10-19 14:48 UTC, tahmeedshah commented on app/views/countries/country-profile.html
> -
This is due to prev commit.

2020-10-19 14:48 UTC, tahmeedshah commented on app/views/countries/country-profile.html
> -</div>
This is because of prev commit.

2020-10-19 15:46 UTC, blaisefonseca approved these changes

2020-10-19 17:29 UTC, merged