Features/bch/hover effect
scbd/absch.cbd.int pull request #388
Opened 2020-10-20 16:05 UTC by tahmeedshah

2020-10-20 19:41 UTC, blaisefonseca commented on app/components/scbd-angularjs-controls/form-control-directives/hover-effect.js
> +                        element.children("ul").attr("style", 'display:block');
can you apply a class instead of the style, because if the ul element has any inline style it will be removed on mouseout evt.

2020-10-20 19:41 UTC, blaisefonseca commented on app/components/scbd-angularjs-controls/form-control-directives/hover-effect.js
> +                element.children("ul").removeAttr("style");
same remove the class instead of the style

2020-10-21 06:01 UTC, tahmeedshah commented on app/components/scbd-angularjs-controls/form-control-directives/hover-effect.js
> +                element.children("ul").removeAttr("style");
applied class instead of the style

2020-10-21 06:01 UTC, tahmeedshah commented on app/components/scbd-angularjs-controls/form-control-directives/hover-effect.js
> +                        element.children("ul").attr("style", 'display:block');
applied class instead of the style

2020-10-23 17:18 UTC, blaisefonseca requested changes
the hover directive cannot be dependent on authentication

2020-10-23 17:18 UTC, blaisefonseca commented on app/components/scbd-angularjs-controls/form-control-directives/hover-effect.js
> +        restrict: 'EAC',
we are no longer using directive by class, only EA

2020-10-23 17:18 UTC, blaisefonseca commented on app/components/scbd-angularjs-controls/form-control-directives/hover-effect.js
> +                if(!element.hasClass('true') && attr.isauthenticated != undefined){
there is no relation between hover directive and authentication

2020-10-26 14:24 UTC, closed without merging