Features/bch/solr query
scbd/absch.cbd.int pull request #389
Opened 2020-10-20 18:22 UTC by blaisefonseca

2020-10-20 19:10 UTC, sbilodeau commented on app/services/solr.js
> +	function unescapeCaret(value) {
this function should probably not part of the solr service. this is specific to your search design

2020-10-20 19:23 UTC, sbilodeau requested changes
when youhave multiple valuea passes to solr with space (OR ???) you should escape each value then join them with space

2020-10-20 19:23 UTC, sbilodeau commented on app/views/forms/edit/abs/edit-absNationalReport.js
> +                 ' AND schema_s:(' + solr.escape(natSchemas.join(' ')) + ')';
escape each value then then join(). otherwise you may end up escaping `space`
```suggestion
                 ' AND schema_s:(' + _.map(natSchemas, solr.escape).join(' ') + ')';
```

2020-10-20 19:23 UTC, sbilodeau commented on app/views/forms/edit/document-selector.js
> +                var fieldQueries = ["schema_s:"+ schema] // cannot escape for backward compatibility
why?

2020-10-20 19:23 UTC, sbilodeau commented on app/views/forms/edit/document-selector.js
> +                    'query'      : queryField + ':("' + solr.escape(identifiers.join('" "')) +'")',
same here escape then join
```suggestion
                    'query'      : queryField + ':("' +_.map(identifiers,solr.escape).join('" "') +'")',
```

2020-10-20 19:23 UTC, sbilodeau commented on app/views/forms/view/bch/view-lmo-gene.directive.js
> +						query 	: "identifier_s:(" +solr.escape(geneIdentifiers.join(' ')) + ")",
```suggestion
						query 	: "identifier_s:(" +_.map(geneIdentifiers, solr.escape).join(' ') + ")",
```

2020-10-20 19:23 UTC, sbilodeau commented on app/views/register/admin/ircc-counts.js
> +                        var endDate     = solr.escape($scope.filters.endDate ? $scope.filters.endDate + 'T23:59:59.999Z' : '*');
is the star `*` must be escaped?

2020-10-20 19:23 UTC, sbilodeau commented on app/views/register/admin/ircc-counts.js
> +                        nationalRecordsQuery.query += ' AND government_s:(' + solr.escape($scope.filters.countries.join(' ')) + ')';
```suggestion
                        nationalRecordsQuery.query += ' AND government_s:(' +_.map($scope.filters.countries, solr.escape).join(' ') + ')';
```

2020-10-20 19:23 UTC, sbilodeau commented on app/views/register/manage/stats.js
> +                                    solr.escape(_.without(appConfigService.nationalSchemas, "contact", "focalPoint").join(' ')) +
```suggestion
                                    _(appConfigService.nationalSchemas).without("contact", "focalPoint").map(solr.escape).value().join(' ') + 
```

2020-10-20 19:23 UTC, sbilodeau commented on app/views/register/manage/stats.js
> +                                    searchQuery.query = "id:(" + solr.escape(solrIds.join(' ')) + ') AND NOT virtual_b';
```suggestion
                                    searchQuery.query = "id:(" + _.map(solrIds, solr.escape).join(' ') + ') AND NOT virtual_b';
```

2020-10-20 19:23 UTC, sbilodeau commented on app/views/register/record-list.js
> +                        filter = '_ownership_s:("' + solr.escape(($rootScope.user.userGroups||[]).join('" "')) + '")'
```suggestion
                        filter = '_ownership_s:("' + _.map($rootScope.user.userGroups||[], solr.escape).join('" "') + '")'
```

2020-10-20 19:23 UTC, sbilodeau commented on app/views/search/search-directive.js
> +                                            subQuery = field + ':(' + solr.escape(ids.join(' ')) + ')';
```suggestion
                                            subQuery = field + ':(' + _.map(ids, solr.escape).join(' ') + ')';
```

2020-10-22 19:00 UTC, blaisefonseca commented on app/views/register/admin/ircc-counts.js
> +                        var endDate     = solr.escape($scope.filters.endDate ? $scope.filters.endDate + 'T23:59:59.999Z' : '*');
no because it has a meaning in solr, if escaped it will be treated as string query

2020-10-22 19:04 UTC, sbilodeau commented on app/views/register/admin/ircc-counts.js
> +                        var endDate     = solr.escape($scope.filters.endDate ? $scope.filters.endDate + 'T23:59:59.999Z' : '*');
then you should change your code because `'*'` is inside the parenthesis of the escape function 
```suggestion
                        var startDate   = $scope.filters.startDate ? solr.escape($scope.filters.startDate + 'T00:00:00.000Z') : '*';
                        var endDate     = $scope.filters.endDate ?  solr.escape($scope.filters.endDate + 'T23:59:59.999Z') : '*';
```

2020-10-22 20:46 UTC, blaisefonseca commented on app/services/solr.js
> +	function unescapeCaret(value) {
used local regex instead of global fn

2020-10-23 19:50 UTC, blaisefonseca commented on app/views/forms/edit/document-selector.js
> +                var fieldQueries = ["schema_s:"+ schema] // cannot escape for backward compatibility
initially it was suppose to just accept schema name, but somewhere we started passing query which will break if the value is escaped. I do have plans to changes this behavior in future.

2020-10-26 13:24 UTC, sbilodeau commented on app/views/forms/edit/document-selector.js
> +                var fieldQueries = ["schema_s:"+ schema] // cannot escape for backward compatibility
ok no problem. make sure to take a note of this to fix it in the future!

2020-10-26 20:45 UTC, sbilodeau commented on app/views/countries/country-profile-directive.js
> +                        query   : 'schema_s:(' + solr.escape(nationalSchemas.join(' ')) +') AND government_s:' + solr.escape(code),
I forgot this one!
```suggestion
                        query   : 'schema_s:(' +_.map(nationalSchemas, solr.escape).join(' ') +') AND government_s:' + solr.escape(code),
```

2020-10-26 20:49 UTC, sbilodeau commented on app/views/reports/bch/lmo-decisions-risk-assessments.js
> +			searchQuery		= searchQuery.replace(/\\^\d+(\s|$)/g,   '^');
can you add a comment to explain why you are unescaping?

2020-10-26 20:52 UTC, blaisefonseca commented on app/views/reports/bch/lmo-decisions-risk-assessments.js
> +			searchQuery		= searchQuery.replace(/\\^\d+(\s|$)/g,   '^');
```suggestion
// unescape ^ so that users can add boosting to the query using solr syntax
			searchQuery		= searchQuery.replace(/\\^\d+(\s|$)/g,   '^');
```

2020-10-26 20:55 UTC, sbilodeau approved these changes

2020-10-26 21:13 UTC, randyhoulahan approved these changes

2020-10-26 21:13 UTC, merged