Add loading image in the login button
scbd/absch.cbd.int pull request #400
Opened 2020-10-31 14:40 UTC by tahmeedshah

2020-10-31 15:06 UTC, blaisefonseca requested changes
can you also disable email and password fields when waiting==true

2020-10-31 15:06 UTC, blaisefonseca commented on app/components/scbd-branding/directives/header/login.html
> +                      <i class="fa fa-spin fa-spinner" ng-if="waiting"></i>Sign in to your account
```suggestion
                      <i class="fa fa-spin fa-spinner" ng-if="waiting"></i> Sign in to your account
```

2020-11-02 13:54 UTC, blaisefonseca approved these changes

2020-11-02 14:17 UTC, sbilodeau approved these changes

2020-11-02 14:17 UTC, merged