BCH-display of text having HTML tags-Devdesk-447
scbd/absch.cbd.int pull request #401
Opened 2020-11-01 07:00 UTC by tahmeedshah

2020-11-02 13:57 UTC, blaisefonseca approved these changes

2020-11-02 14:54 UTC, sbilodeau requested changes
Please remove HTML to `address` field.

Also make sure that migration script convert `OrganizationName` to text. Currently it may contain html escape: see https://jira.cbd.int/projects/DEVDESK/queues/custom/106/DEVDESK-447

2020-11-02 14:54 UTC, sbilodeau commented on app/views/forms/view/view-contact.directive.html
> +				<div class="km-pre" ng-bind-html="document.address | lstring:locale"></div>
The address must be in plain text. `ng-bind-html` & `km-pre` are conflicting here.
There is probably a problem in the old BCH or the migration script which may keep/inject html code into the `address` field.

@blaisefonseca  please make sure the `address` field is converted to text using Html Utility `ToText()` function.

2020-11-04 16:41 UTC, sbilodeau approved these changes

2020-11-04 17:11 UTC, blaisefonseca approved these changes

2020-11-04 17:17 UTC, merged