if a BCP record exists notify user on new entry
scbd/absch.cbd.int pull request #413
Opened 2020-11-05 20:28 UTC by tahmeedshah

if a BCP record exists notify user on new entry
when the user tries to create a new record-DEVDESK-466

2020-11-06 20:35 UTC, blaisefonseca requested changes
please rebase with master

2020-11-06 20:35 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-country-profile.directive.js
> +							query   : 'schema_s:countryProfile AND government_s:' + government.toLowerCase()
government need to be solr.escape

2020-11-09 14:29 UTC, blaisefonseca approved these changes

2020-11-09 14:43 UTC, sbilodeau approved these changes

2020-11-09 14:44 UTC, merged