Bch submissions changes
scbd/absch.cbd.int pull request #428
Opened 2020-11-26 05:39 UTC by tahmeedshah

DEVDESK-513
BCH-Submissions-remove "mandatory" from “Notifications” and “Related record(s)” in Edit

DEVDESK-514
BCH-Submissions-In Edit "Thematic area(s)" is missing "Other" option

DEVDESK-515
BCH- Submissions- "Cosmetic" changes in Edit and View

2020-11-26 15:54 UTC, blaisefonseca requested changes
can we not use auto format please, can you revert the formatting changes?

2020-11-26 16:00 UTC, blaisefonseca approved these changes
ignore my previous comment

2020-11-26 16:53 UTC, blaisefonseca commented on app/views/forms/edit/edit-submission.html
> +                                                </div>
```suggestion
                                                caption="Relevant organization(s) " required>
                                                <div document-selector ng-disabled="document.government"
                                                    question="organizations" type="radio" query="organizationQuery"
                                                    ng-change="onNotificationSelected()" skip-government="true"
                                                    ng-model="document.organizations" allow-new-schema="organization">
                                                </div>
```

2020-11-26 17:47 UTC, blaisefonseca commented on app/views/forms/edit/edit-submission.html
> +                                                </div>
@tahmeedshah  the field has been changed from `organization` to `organizations`, can you please update edit and view forms

2020-11-30 14:30 UTC, sbilodeau approved these changes

2020-11-30 14:41 UTC, merged