update text for (i)'s
scbd/absch.cbd.int pull request #432
Opened 2020-12-07 20:45 UTC by tahmeedshah

update (i)'s text for BCH and ABSCH.

2020-12-07 21:38 UTC, blaisefonseca commented on app/views/register/dashboard.html
> +
if the message is same no need to have separate messages for abs and bch

2020-12-07 21:42 UTC, blaisefonseca commented on app/views/register/dashboard.html
> +                                    data-title="Reference records include a number of ABS-related resources and information that can be submitted by any registered user and are validated by the Secre
update the national and reference records text in search page as well

2020-12-07 21:43 UTC, blaisefonseca requested changes
I have put two comments

2020-12-08 21:18 UTC, blaisefonseca requested changes
`app/app-data/realm-configurations-bch.json` `app/app-data/realm-configurations-absch.json` these two files need to be under individual protocol folders

should be
`app/app-data/bch/realm-configuration.json`
`app/app-data/abs/realm-configuration.json`

2020-12-08 21:25 UTC, blaisefonseca requested changes
`Contact` is missing description

2020-12-10 15:54 UTC, blaisefonseca approved these changes

2020-12-10 16:05 UTC, sbilodeau approved these changes

2020-12-10 16:41 UTC, merged