add the titlePlural property
scbd/absch.cbd.int pull request #442
Opened 2020-12-16 20:16 UTC by tahmeedshah

DEVDESK-547
BCH-Plural form of list of records

2020-12-16 20:28 UTC, blaisefonseca commented on app/app-data/abs/realm-configuration.json
> +            "en": "National Biosafety Websites or Databases"
this abs file

2020-12-16 20:28 UTC, blaisefonseca commented on app/app-data/abs/realm-configuration.json
> +            "en": "Biosafety Organizations"
wrong file

2020-12-16 20:30 UTC, blaisefonseca commented on app/app-data/bch/realm-configuration.json
> +            "en": ""
```suggestion
            "en": "Capacity Building Initiatives"
```

2020-12-16 20:31 UTC, blaisefonseca commented on app/app-data/bch/realm-configuration.json
> +          }
remove empty object
```suggestion
```

2020-12-16 20:31 UTC, blaisefonseca requested changes
please see comments

2020-12-17 07:06 UTC, tahmeedshah commented on app/app-data/bch/realm-configuration.json
> +          }
corrected as suggested

2020-12-17 16:42 UTC, blaisefonseca commented on app/app-data/bch/realm-configuration.json
> +          "shortCode": "BVLR",
```suggestion
          "shortCode": "VLR",
```

2020-12-17 16:46 UTC, blaisefonseca approved these changes

2020-12-17 16:47 UTC, merged