BCH REPORT: show the login dialog if the use is not logged
scbd/absch.cbd.int pull request #449
Opened 2020-12-22 10:42 UTC by tahmeedshah

https://jira.cbd.int/browse/DEVDESK-548
For reference.

2020-12-22 14:43 UTC, randyhoulahan approved these changes

2020-12-22 14:51 UTC, randyhoulahan approved these changes

2020-12-22 14:53 UTC, randyhoulahan approved these changes
Approved for #3 & #4 of https://jira.cbd.int/browse/DEVDESK-548

2020-12-23 16:11 UTC, blaisefonseca commented on app/views/directives/document-metadata-directive.js
> +                    else {
you will have to track the login, so that after the login is successful the report dialog is open immediately.
1. before logindialog.show add event
```
var signInEvent = $rootScope.$on('signIn', function(){
     // login successful,
    2. show report record dialog
});
```
3. remove above listener when logindialog.close 
 ` signInEvent()`

2020-12-23 18:08 UTC, tahmeedshah commented on app/views/directives/document-metadata-directive.js
> +                    else {
resolved.

2020-12-30 18:59 UTC, sbilodeau requested changes
#1 of https://jira.cbd.int/browse/DEVDESK-548 is not fixed. I wrote to Anastasia for clarification/suggestion on a generic sentence

2021-01-04 16:25 UTC, blaisefonseca commented
@tahmeedshah 
1. can you convert the reported record directive to open in dialog instead of inline please
2. for now use realm condition to display BCH OR ABSCH while Anastasia responds.
3. when the login dialog opens and if the user clicks on cancel we need to remove the signIn listener else if the user signs in from some other place this event will be raised. 
```
$('#myModal').on('hidden.bs.modal', function () {
   //remove event
});
```
we are using ngDialog for new dialogs which has much better API, if you can use it will be great.

2021-01-05 18:57 UTC, blaisefonseca commented on app/views/directives/report-record.html
> +            </h3>
```suggestion
            <h3 class="modal-title">
                Report record: <span ng-if="title" ng-bind="title"></span>
            </h3>
```

2021-01-05 19:03 UTC, blaisefonseca requested changes
one small change

2021-01-07 14:42 UTC, blaisefonseca approved these changes

2021-01-07 14:43 UTC, merged