BCH: Country's Decision (DEC) updates
scbd/absch.cbd.int pull request #451
Opened 2020-12-23 16:58 UTC by tahmeedshah

https://jira.cbd.int/projects/DEVDESK/queues/custom/77/DEVDESK-540
for reference

2020-12-30 19:16 UTC, sbilodeau approved these changes

2021-01-04 19:47 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-biosafety-decision.directive.html
> +												</div>
can we display this EU only message to EU member states only
![image](https://user-images.githubusercontent.com/7049230/103573109-b21bdd00-4e9b-11eb-8074-17dd5aab3ad0.png)

2021-01-04 20:21 UTC, blaisefonseca requested changes

2021-01-07 14:46 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-biosafety-decision.directive.js
> +                $scope.getCountryTerm = function (code) {
` $scope.getCountryTerm ` no need to be on $scope, can be local function

2021-01-07 14:47 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-biosafety-decision.directive.js
> +                  thesaurusService.getTerms(solr.escape('eu'),{relations:true})
can you check if the current government == 'eu' than just plainly set isEUMember=true and not run the remaining code

2021-01-07 15:01 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-biosafety-decision.directive.js
> +                  }
u can just use `$scope.isEUMember = _.has(o.narrowerTerms, {item:code})` // https://lodash.com/docs/3.10.1#some

2021-01-08 06:56 UTC, tahmeedshah commented on app/views/forms/edit/bch/directives/edit-biosafety-decision.directive.js
> +                $scope.getCountryTerm = function (code) {
removed getCountryTerm function and simplify the onCountryChange function

2021-01-08 06:58 UTC, tahmeedshah commented on app/views/forms/edit/bch/directives/edit-biosafety-decision.directive.js
> +                  thesaurusService.getTerms(solr.escape('eu'),{relations:true})
updated at:
https://github.com/scbd/absch.cbd.int/pull/451/commits/c39ca94a090542139baef64321d60c0d2aee8b42

2021-01-08 06:59 UTC, tahmeedshah commented on app/views/forms/edit/bch/directives/edit-biosafety-decision.directive.js
> +                  }
updated at:
https://github.com/scbd/absch.cbd.int/pull/451/commits/c39ca94a090542139baef64321d60c0d2aee8b42

2021-01-15 21:39 UTC, blaisefonseca requested changes
@tahmeedshah  FYI i am doing this changes

2021-01-29 20:55 UTC, randyhoulahan approved these changes

2021-01-29 21:14 UTC, merged