BCH Capacity-Building-Initiative changes
scbd/absch.cbd.int pull request #452
Opened 2020-12-29 10:58 UTC by tahmeedshah

2020-12-30 19:19 UTC, sbilodeau commented
@tahmeedshah can you provide JIRA Issue #?

2020-12-30 19:25 UTC, tahmeedshah commented
Jira issue # : DEVDESK-550
             BCH - Capacity-Building Initiative (Activity, Project or Academic Training
             https://jira.cbd.int/projects/DEVDESK/queues/custom/77/DEVDESK-550

2021-01-20 21:00 UTC, blaisefonseca commented on app/views/forms/edit/edit-capacityBuildingInitiative.html
> +										<div class="row" ng-if="isABS">
Contacts is mandatory but after validation its not highlighted in red

![image](https://user-images.githubusercontent.com/7049230/105233984-928de100-5b38-11eb-8525-8828782950c2.png)

2021-01-21 15:07 UTC, blaisefonseca requested changes
please see comments

2021-01-21 15:07 UTC, blaisefonseca commented on app/views/forms/edit/edit-capacityBuildingInitiative.js
> +                return $http.get("/api/v2013/thesaurus/domains/Capacity Building Project Funding Types/terms", { cache: true })
move to thesaurusService

2021-01-21 15:07 UTC, blaisefonseca commented on app/views/forms/edit/edit-capacityBuildingInitiative.js
> +                });
remove enumerable reference, should work without it.

2021-01-21 15:07 UTC, blaisefonseca commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +			<label>Title {{isBCH ? 'of the initiative':''}}</label>
use seprate span for abs and bch

2021-01-21 15:07 UTC, blaisefonseca commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +				<i ng-show="item.name && item.url.indexOf('/api/v2013/documents/')<0">({{item.url}})</i>
use km-link-list control

2021-01-21 15:07 UTC, blaisefonseca commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +			<label>Status {{isBCH ? '':'of the document'}}</label>
use span for abs and bch

2021-01-21 15:07 UTC, blaisefonseca commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +			<label>{{isBCH ? 'Main':''}} Target group(s)/beneficiary(ies)</label>
use span for abs and bch

2021-01-21 15:07 UTC, blaisefonseca commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +				<li ng-repeat="term in document.cpbThematicAreas">{{term | term:locale}}</li>
ng-bind

2021-01-21 15:07 UTC, blaisefonseca commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +			<label>{{isBCH ? 'Primary funding-source(s)':'Core funding-source(s)'}}</label>
use span for abs and bch

2021-01-21 15:07 UTC, blaisefonseca commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +			<label>{{isBCH ? 'Co-funding source(s)':'Co-financing source(s)'}}</label>
use span for abs and bch

2021-01-21 15:07 UTC, blaisefonseca commented on app/views/forms/edit/edit-capacityBuildingInitiative.js
> +            languages : thesaurusService.getDomainTerms('unLanguages')
can u convert the domain names to camel case, please check for app wide reference

2021-01-21 15:07 UTC, blaisefonseca commented on app/views/forms/edit/edit-capacityBuildingInitiative.js
> +    app.controller("editCapacityBuildingInitiative", ["$scope", "$http", "$filter", "$q", "$routeParams", "$controller","$location", "Thesaurus", "Enumerable", "underscore", "realm","thesaurusService
use lodash instead of underscore

2021-01-21 15:07 UTC, blaisefonseca commented on app/views/forms/edit/edit-capacityBuildingInitiative.html
> +													<legend>{{isBCH ? '20':'22'}}. Notes</legend>
use span for abs and bch

2021-01-22 18:16 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.js
> +            languages : thesaurusService.getDomainTerms('unLanguages')
I think we should do this activity in a new PR because many files of other CF need changes for this.

2021-01-22 22:33 UTC, blaisefonseca commented on app/services/thesaurus-service.js
> +                cbiStatus       : '4E7731C7-791E-46E9-A579-7272AF261FED',
can you make sure this changes are not affecting other places

2021-01-22 22:36 UTC, blaisefonseca commented on app/views/forms/edit/edit-capacityBuildingInitiative.js
> +            languages : thesaurusService.getDomainTerms('unLanguages')
yes lets do a separate PR for updating the case

2021-01-23 16:33 UTC, tahmeedshah commented on app/services/thesaurus-service.js
> +                cbiStatus       : '4E7731C7-791E-46E9-A579-7272AF261FED',
Yes, I checked,  these changes are not affecting other places.

2021-01-29 14:50 UTC, blaisefonseca commented
https://github.com/scbd/absch.cbd.int/pull/452/files#diff-bba576348c6ba82eaadfd1bce46c1cb3af784ee73de106953366fc9593b65319R187%20

pass true here $scope.setDocument({}, true);

2021-01-29 15:04 UTC, blaisefonseca requested changes
few more issues

2021-01-29 15:41 UTC, blaisefonseca commented
when national is selected, hide text Geographical or political/economic group(s) or Country(ies) and make countries label mandatory
![image](https://user-images.githubusercontent.com/7049230/106295409-63edc580-621e-11eb-95c7-bcb1a82391b1.png)

2021-01-29 15:43 UTC, blaisefonseca commented
when community is selected country also need to be visible
![image](https://user-images.githubusercontent.com/7049230/106295682-c0e97b80-621e-11eb-8677-ff8c0c7dabe6.png)

2021-01-29 16:08 UTC, blaisefonseca commented
use absch categories for bch as well
            
![image](https://user-images.githubusercontent.com/7049230/106298701-3571e980-6222-11eb-9106-5163bf05038b.png)

2021-01-29 19:01 UTC, tahmeedshah commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +				<span ng-bind="document.title | lstring:locale"></span>
Updated for km-value-ml directive

2021-01-29 19:02 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.html
> +								</div>
trimmed the text in validation control

2021-01-29 19:03 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.html
> +										<div class="row" ng-if="isABS">
used conditions for label

2021-01-29 19:04 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.html
> +													<div km-term-check required show-description="true" name="fundingSourceTypes" ng-model="document.fundingSourceTypes" terms="options.fundingSources()" binding-type="term[]"></div>
duplicate removed

2021-01-29 19:04 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.html
> +														<span ng-if="isABS">15. Co-financing source(s)</span>
used coFinancingSources

2021-01-29 19:04 UTC, tahmeedshah commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +		<div ng-if="isABS" ng-show="document.contacts">
removed ng-show

2021-01-29 19:05 UTC, tahmeedshah commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +		<div ng-if="isABS" ng-show="document.projectDocument">
removed ng-show

2021-01-29 19:05 UTC, tahmeedshah commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +				<div class="km-value km-pre"> <span ng-bind="document.bestPractices | lstring:locale"></span></div>
used km-value-ml control

2021-01-29 21:19 UTC, blaisefonseca commented
@tahmeedshah  I am merging this PR, but please add the pending changes to new PR

2021-01-29 21:19 UTC, merged

2021-02-04 14:58 UTC, naveedshahji commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +			<label>{{isBCH ? 'Primary funding-source(s)':'Core funding-source(s)'}}</label>
this is done

2021-02-04 16:48 UTC, tahmeedshah commented on app/routes/bch.js
> +               whenAsync('/register/CBA/new',                   {templateUrl: 'views/forms/edit/edit-capacityBuildingInitiative.html',      label:'New',  param:'true', resolveController: true,documen
removed CBA

2021-02-04 16:49 UTC, tahmeedshah commented on app/services/thesaurus-service.js
> +                cBI_types1       : '5CA7AACE-CB79-4146-BF12-B3B1955AFF17', // used in BCH CBI scope of activity
All domain terms are renamed

2021-02-04 16:50 UTC, tahmeedshah commented on app/services/thesaurus-service.js
> +                maintargetzgroup : '2560F889-AB81-40BF-B7C4-97B34A5B8D75',
All domain terms are renamed

2021-02-04 16:52 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.html
>  													<div km-textbox-ml required ng-model="document.title" locales="document.header.languages"></div>
added two spans for ABS and BCH:
<span ng-if="isABS">1. Title</span>
<span ng-if="isBCH">1. Title of the initiative</span>

2021-02-04 16:54 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.html
> +											</div>
used allow-file="false"

2021-02-04 16:55 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.html
> +														<div class="help-block">All BCH common formats are available on the Dashboard of the Submit page in the BCH</div>
help block removed

2021-02-04 16:55 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.html
> +												<div class="km-control-group" required name="geographicScope" caption="{{isBCH ? '4':'3'}}. Geographic Scope">
done as suggested

2021-02-04 16:56 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.html
> +															<!-- <organization-selector multiple ng-model="document.implementingAgencies" locales="document.header.languages" caption="{{'Add an organization »'}}"></organization-selector> -->
removed commented

2021-02-04 16:56 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.html
> +															<!-- <organization-selector multiple ng-model="document.executingAgencies" locales="document.header.languages" caption="{{'Add an organization »'}}"></organization-selector> -->
removed commented

2021-02-04 16:57 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.html
> +													<div km-term-check show-description="true" name="fundingSourceTypes" ng-model="document.fundingSourceTypes" terms="options.fundingSources()" binding-type="term[]"></div>
used ng-required="isABS"

2021-02-04 16:58 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.js
>  define(['app', 'underscore', 'views/forms/edit/edit', '../view/view-capacity-building-initiative.directive',
updated underscore to lodash

2021-02-04 16:59 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.js
> +                return $http.get("/api/v2013/thesaurus/domains/Capacity Building Project Funding Types/terms", { cache: true })
moved to thesaurusService

2021-02-04 17:00 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.js
> +                });
removed enumerable reference

2021-02-04 17:01 UTC, tahmeedshah commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +			<label>Title {{isBCH ? 'of the initiative':''}}</label>
used seprate span for abs and bch

2021-02-04 17:01 UTC, tahmeedshah commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +				<i ng-show="item.name && item.url.indexOf('/api/v2013/documents/')<0">({{item.url}})</i>
used km-link-list control

2021-02-04 17:03 UTC, tahmeedshah commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +			<label>Status {{isBCH ? '':'of the document'}}</label>
used span for abs and bch

2021-02-04 17:03 UTC, tahmeedshah commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +			<label>{{isBCH ? 'Main':''}} Target group(s)/beneficiary(ies)</label>
used span for abs and bch

2021-02-04 17:04 UTC, tahmeedshah commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +				<li ng-repeat="term in document.cpbThematicAreas">{{term | term:locale}}</li>
<li ng-repeat="term in document.cpbThematicAreas" ng-bind="term | term:locale"></li>

2021-02-04 17:05 UTC, tahmeedshah commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +			<label>{{isBCH ? 'Primary funding-source(s)':'Core funding-source(s)'}}</label>
used span for abs and bch

2021-02-04 17:06 UTC, tahmeedshah commented on app/views/forms/view/view-capacity-building-initiative.directive.html
> +			<label>{{isBCH ? 'Co-funding source(s)':'Co-financing source(s)'}}</label>
used span for abs and bch

2021-02-04 17:06 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.js
> +            languages : thesaurusService.getDomainTerms('unLanguages')
done as suggested

2021-02-04 17:07 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.js
> +    app.controller("editCapacityBuildingInitiative", ["$scope", "$http", "$filter", "$q", "$routeParams", "$controller","$location", "Thesaurus", "Enumerable", "underscore", "realm","thesaurusService
updated underscore to lodash

2021-02-04 17:07 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.html
> +													<legend>{{isBCH ? '20':'22'}}. Notes</legend>
used span for abs and bch

2021-02-04 17:09 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingInitiative.html
> +	.full-length{
updated as suggested