BCH : Virtual Library Record
scbd/absch.cbd.int pull request #453
Opened 2020-12-29 16:43 UTC by tahmeedshah

2020-12-30 19:20 UTC, sbilodeau commented
@tahmeedshah can you provide JIRA Issue #?

2020-12-30 19:29 UTC, tahmeedshah commented
Jira issue # DEVDESK-564
BCH : Virtual Library record
https://jira.cbd.int/projects/DEVDESK/queues/custom/77/DEVDESK-564

2021-01-05 17:29 UTC, blaisefonseca commented on app/views/forms/edit/edit-resource-schema-base-directive.html
> +												</select>
can we put month name? and also display month name in view
![image](https://user-images.githubusercontent.com/7049230/103678477-92df8700-4f51-11eb-8ef0-ea34aa1199b1.png)

2021-01-05 17:30 UTC, blaisefonseca commented on app/views/forms/edit/edit-resource-schema-base-directive.html
> +									<div class="row" ng-if="isBCH">
Languages field is missing

2021-01-05 17:33 UTC, blaisefonseca commented
this needs to be multiple, please see Alternate scientific name (synonyms) in http://localhost:2010/register/ORGA/new
![image](https://user-images.githubusercontent.com/7049230/103678813-07b2c100-4f52-11eb-82da-01477fde4dba.png)

2021-01-27 18:04 UTC, blaisefonseca commented
apply this code in `app/components/scbd-angularjs-controls/form-control-directives/km-control-group.js` for the error control color issue

$scope.hasWarning = function() {  //default behavior

					if($scope.name) {
						var validationReport = findReportInParent($scope, 0)||{}
						return !!_.findWhere(validationReport.warnings, { property : $scope.name });
					}

					return false; //default behavior
				};

				$scope.hasError = function() {  //default behavior
					
					if($scope.name) {
						var validationReport = findReportInParent($scope, 0)||{}
						return !!_.findWhere(validationReport.errors, { property : $scope.name });
					}

					return false;
				};

				$scope.isRequired = function() {
					return $scope.required !== undefined && $scope.required.toString()!="false";
				};

				function findReportInParent($scope, level){
					if(level < 5 && $scope.$parent){
						if($scope.$parent.validationReport)
							return $scope.$parent.validationReport
						
						return findReportInParent($scope.$parent, level++);
					}

					return;
				}

2021-02-03 21:31 UTC, blaisefonseca commented
`AuthorInfo` field is missing

2021-02-03 21:33 UTC, blaisefonseca commented
can these sub-fields aligned to left
![image](https://user-images.githubusercontent.com/7049230/106812373-91cb7380-663d-11eb-9b65-157b5da0c4e1.png)

2021-02-03 21:39 UTC, blaisefonseca commented
move obtain the resource to Access to resource section.
![image](https://user-images.githubusercontent.com/7049230/106812912-52e9ed80-663e-11eb-919b-205e581f1a26.png)

2021-02-03 22:03 UTC, blaisefonseca commented on app/views/forms/edit/edit-resource-schema-base-directive.js
> +				$scope.monthNames = ['January', 'February', 'March', 'April', 'May','June', 'July', 'August', 'September','October', 'November', 'December'];
we will not be able to translate, can we put 12 options in html instead of ng-repeat on options?

2021-02-03 22:04 UTC, blaisefonseca commented on app/views/forms/edit/edit-resource-schema-base-directive.js
> +					return $scope.sanitizeDocument(document);
clean non app fields for eg. when abs make sure bch fields are set to undefined and vice-versa

2021-02-03 22:05 UTC, blaisefonseca commented on app/views/forms/edit/edit-resource-schema-base-directive.js
> +				});
can we use ng-change instead of watch?

2021-02-03 22:06 UTC, blaisefonseca commented on app/views/forms/view/view-resource.directive.html
>  		</div>
authorsInfo field missing

2021-02-03 22:08 UTC, blaisefonseca commented on app/views/forms/view/view-resource.directive.html
> +		</div>
display together YYYY-MM format, its not lstirng so normal span binding will do

2021-02-03 22:11 UTC, blaisefonseca commented on app/views/forms/view/view-resource.directive.html
> +			<km-value-ml value="document.summary" locales="locale" html></km-value-ml>
can we be consistent in using 
```
<div class="row">
	<div class="col-sm-12"></div>
</div>
```

2021-02-03 22:12 UTC, blaisefonseca commented on app/views/forms/view/view-resource.directive.html
> +					<li ng-repeat="term in document.resourceTypes"><span ng-bind="term | term | lstring:locale"></span></li>
c
```suggestion
					<li ng-repeat="val in document.resourceTypes"><span ng-bind="val | term | lstring:locale"></span></li>
```

2021-02-03 22:14 UTC, blaisefonseca requested changes
there few more changes required!

2021-02-04 16:31 UTC, tahmeedshah commented on app/views/forms/edit/edit-resource-schema-base-directive.js
> +				$scope.monthNames = ['January', 'February', 'March', 'April', 'May','June', 'July', 'August', 'September','October', 'November', 'December'];
added 12 options for months  in html instead of ng-repeat

2021-02-04 16:32 UTC, tahmeedshah commented on app/views/forms/edit/edit-resource-schema-base-directive.js
> +					return $scope.sanitizeDocument(document);
fields are set to undefined

2021-02-04 16:33 UTC, tahmeedshah commented on app/views/forms/edit/edit-resource-schema-base-directive.js
> +				});
replaced watch

2021-02-04 16:33 UTC, tahmeedshah commented on app/views/forms/view/view-resource.directive.html
>  		</div>
authorsInfo added .

2021-02-04 16:34 UTC, tahmeedshah commented on app/views/forms/view/view-resource.directive.html
> +		</div>
make together YYYY-MM

2021-02-04 16:36 UTC, tahmeedshah commented on app/views/forms/view/view-resource.directive.html
> +			<km-value-ml value="document.summary" locales="locale" html></km-value-ml>
I think we should create a separate PR for this task.

2021-02-04 16:36 UTC, tahmeedshah commented on app/views/forms/view/view-resource.directive.html
> +					<li ng-repeat="term in document.resourceTypes"><span ng-bind="term | term | lstring:locale"></span></li>
renamed confusing term

2021-02-04 20:06 UTC, blaisefonseca commented on app/views/forms/edit/edit-resource-schema-base-directive.js
> +							document.keywords = _( $scope.keywords ).pluck( 'value' ).compact().value();
pluck will not work with new _ version, please make a note

2021-02-04 20:10 UTC, blaisefonseca commented on app/views/forms/edit/edit-resource-schema-base-directive.js
> +						if ( !_.isEmpty( $scope.keywords )  && !$scope.isABS)
if(!isBCH)
set all bch fields to undefined for eg. addressLmoCategories etc

2021-02-04 20:13 UTC, blaisefonseca commented on app/views/forms/view/view-resource.directive.html
> +			<div class="km-value"><span ng-bind="document.publicationYear"></span>-<span ng-bind="monthNames[document.publicationMonth-1]"></span></div>
can this be one block and just put condition when bch to show publicationMonth

2021-02-04 20:13 UTC, blaisefonseca requested changes
we are close, just few more changes

2021-02-04 20:14 UTC, blaisefonseca commented on app/views/forms/view/view-resource.directive.html
> +			<km-value-ml value="document.summary" locales="locale" html></km-value-ml>
ok sure, please keep a note

2021-02-04 20:20 UTC, blaisefonseca commented on app/views/forms/edit/edit-resource-schema-base-directive.js
> +				});
I still see ng-watch?

2021-02-05 13:34 UTC, tahmeedshah commented on app/views/forms/edit/edit-resource-schema-base-directive.js
> +							document.keywords = _( $scope.keywords ).pluck( 'value' ).compact().value();
pluck replaced with map

2021-02-05 13:34 UTC, tahmeedshah commented on app/views/forms/edit/edit-resource-schema-base-directive.js
> +						if ( !_.isEmpty( $scope.keywords )  && !$scope.isABS)
set all bch fields to undefined if(!isBCH)

2021-02-05 13:35 UTC, tahmeedshah commented on app/views/forms/view/view-resource.directive.html
> +			<div class="km-value"><span ng-bind="document.publicationYear"></span>-<span ng-bind="monthNames[document.publicationMonth-1]"></span></div>
added condition if bch then show publicationMonth

2021-02-05 18:17 UTC, blaisefonseca approved these changes

2021-02-05 18:17 UTC, merged