Change underscore to lodash
scbd/absch.cbd.int pull request #463
Opened 2021-01-25 20:12 UTC by tahmeedshah

2021-02-03 22:15 UTC, blaisefonseca commented
@tahmeedshah if the PR is ready please change status to Ready for review

2021-02-04 15:13 UTC, blaisefonseca commented
was the boot.js updated to use lodah@4.*?
![image](https://user-images.githubusercontent.com/7049230/106913080-a2c5c480-66d1-11eb-8caa-f95f3c81a045.png)

2021-02-04 15:16 UTC, blaisefonseca commented on app/views/report-analyzer/reports.js
> +                $location.url(_.forInRight($location.path(), '/') + '/analyzer');
wrong function, it should be https://lodash.com/docs/4.17.15#trimEnd

2021-02-04 15:17 UTC, blaisefonseca commented
remove underscore factory from service.js
![image](https://user-images.githubusercontent.com/7049230/106913645-34353680-66d2-11eb-9c18-1e62e7402540.png)

2021-02-04 15:22 UTC, blaisefonseca commented
https://github.com/lodash/lodash/wiki/Migrating

2021-02-04 19:27 UTC, blaisefonseca commented on app/js/services.js
no need for the factory please remove

2021-02-04 19:31 UTC, blaisefonseca commented on app/views/forms/edit/edit-capacityBuildingResource.js
remove lodash from controller and put inside define

2021-02-04 19:32 UTC, blaisefonseca commented on app/views/forms/edit/permit-selection-directive.html.js
> +		controller : ["$scope", "$http", "Thesaurus", "$filter", "lodash", "guid",
remove from controller and put inside define

2021-02-04 19:32 UTC, blaisefonseca commented on app/views/forms/edit/permit-selection-directive.js
> +		controller : ["$scope", "$http", "Thesaurus", "$filter", "lodash", "guid",
remove from controller and put inside define

2021-02-04 19:32 UTC, blaisefonseca commented on app/views/forms/edit/warning-message-cna.js
> +           controller: ["$scope", "lodash", "searchService", "solr","$q",
remove from controller and put inside define

2021-02-04 19:37 UTC, blaisefonseca requested changes
some more fixes are required

2021-02-04 19:37 UTC, blaisefonseca commented on app/views/forms/view/abs/view-abs-checkpoint-communique.directive.js
> +		controller: ["$scope", "IStorage", "$http", "$q","lodash","realm", function ($scope, storage, $http, $q, _, realm)
remove from controller and put inside define

2021-02-04 19:37 UTC, blaisefonseca commented on app/views/forms/view/abs/view-abs-national-report.directive.js
> +		controller : ["$scope", "lodash", "commonjs", "$filter", function ($scope, _, commonjs, $filter)
remove from controller and put inside define

2021-02-04 19:37 UTC, blaisefonseca commented on app/views/forms/view/abs/view-abs-permit.directive.js
> +		controller: ["$scope", "IStorage", "$http", "$q","lodash", function ($scope, storage, $http, $q, _)
remove from controller and put inside define

2021-02-04 19:37 UTC, blaisefonseca commented on app/views/help/forms/edit-help.js
> +			["$routeParams", "$scope", "$rootScope", "$q", "lodash", '$http',  '$location', 'commonjs', '$mdDialog',
remove lodash from controller and put inside define

2021-02-04 19:37 UTC, blaisefonseca commented on app/views/help/presentations/presentation.js
> +	["$rootScope", "$location" , "$scope", "$q", "$window", "IStorage", "lodash",
remove lodash from controller and put inside define

2021-02-04 19:37 UTC, blaisefonseca commented on app/views/help/releases.js
> +   ["$rootScope", "$scope", "$q", "lodash",'$http',function ($rootScope, $scope, $q, _, $http) {
remove lodash from controller and put inside define

2021-02-08 18:53 UTC, tahmeedshah commented on app/views/help/releases.js
> +   ["$rootScope", "$scope", "$q", "lodash",'$http',function ($rootScope, $scope, $q, _, $http) {
moved lodash from controller to define

2021-02-08 19:17 UTC, tahmeedshah commented on app/views/report-analyzer/reports.js
> +                $location.url(_.forInRight($location.path(), '/') + '/analyzer');
changed to trimEnd

2021-02-08 19:17 UTC, tahmeedshah commented on app/js/services.js
factory  removed

2021-02-08 19:18 UTC, tahmeedshah commented on app/views/forms/edit/edit-capacityBuildingResource.js
moved lodash from controller to define

2021-02-08 19:18 UTC, tahmeedshah commented on app/views/forms/edit/permit-selection-directive.html.js
> +		controller : ["$scope", "$http", "Thesaurus", "$filter", "lodash", "guid",
moved lodash from controller to define

2021-02-08 19:18 UTC, tahmeedshah commented on app/views/forms/edit/permit-selection-directive.js
> +		controller : ["$scope", "$http", "Thesaurus", "$filter", "lodash", "guid",
moved lodash from controller to define

2021-02-08 19:18 UTC, tahmeedshah commented on app/views/forms/edit/warning-message-cna.js
> +           controller: ["$scope", "lodash", "searchService", "solr","$q",
moved lodash from controller to define

2021-02-08 19:19 UTC, tahmeedshah commented on app/views/forms/view/abs/view-abs-checkpoint-communique.directive.js
> +		controller: ["$scope", "IStorage", "$http", "$q","lodash","realm", function ($scope, storage, $http, $q, _, realm)
moved lodash from controller to define

2021-02-08 19:20 UTC, tahmeedshah commented on app/views/forms/view/abs/view-abs-national-report.directive.js
> +		controller : ["$scope", "lodash", "commonjs", "$filter", function ($scope, _, commonjs, $filter)
moved lodash from controller to define

2021-02-08 19:21 UTC, tahmeedshah commented on app/views/forms/view/abs/view-abs-permit.directive.js
> +		controller: ["$scope", "IStorage", "$http", "$q","lodash", function ($scope, storage, $http, $q, _)
moved lodash from controller to define

2021-02-08 19:21 UTC, tahmeedshah commented on app/views/help/forms/edit-help.js
> +			["$routeParams", "$scope", "$rootScope", "$q", "lodash", '$http',  '$location', 'commonjs', '$mdDialog',
moved lodash from controller to define

2021-02-08 19:21 UTC, tahmeedshah commented on app/views/help/presentations/presentation.js
> +	["$rootScope", "$location" , "$scope", "$q", "$window", "IStorage", "lodash",
moved lodash from controller to define

2021-02-15 19:40 UTC, blaisefonseca approved these changes

2021-02-15 19:45 UTC, merged