Implement the Risk Assessment section in VLR
scbd/absch.cbd.int pull request #472
Opened 2021-02-08 17:00 UTC by tahmeedshah

2021-02-09 21:13 UTC, blaisefonseca requested changes
needs changes

2021-02-09 21:13 UTC, blaisefonseca commented on app/views/forms/edit/edit-resource-schema-base-directive.js
> +						$scope.displayBchRaSubjects = false;
```suggestion
$scope.displayBchRaSubjects = _.some(value||[], {identifier: "FBAF958B-14BF-45DD-BC6D-D34A9953BCEF"};
```

please use `hasRiskAssessmentSubject`

2021-02-09 21:13 UTC, blaisefonseca commented on app/views/forms/view/view-resource.directive.html
> +		<div ng-show="document.bchRaRecommend && document.bchRaRecommend != undefined && isBCH">
if the answer is no than the condition will not be satisfied, just use `document.bchRaRecommend != undefined && isBCH`

2021-02-09 21:13 UTC, blaisefonseca commented on app/views/forms/view/view-resource.directive.html
> +			<label>If “Risk assessment” was indicated as one of the “Thematic areas” in the previous question, please answer to the following question: would you like to recommend
```suggestion
			<label>Would you like to recommend 
```

2021-02-09 21:13 UTC, blaisefonseca commented on app/views/forms/view/view-resource.directive.html
> +				<div ng-if="document.bchRaRecommend">Yes</div>
need to show if the answer was no

2021-02-09 21:13 UTC, blaisefonseca commented on app/views/forms/view/view-resource.directive.html
> +				<label>Which section(s) of the “Guidance” this background material is relevant: </label>
```suggestion
				<label>Which section(s) of the “Guidance” this background material is relevant </label>
```

2021-02-09 21:13 UTC, blaisefonseca commented on app/views/forms/view/view-resource.directive.html
> +				<ul ng-repeat="val in document.regions" class="list">
the ng-repeat needs to be on li and not ul

2021-02-09 21:13 UTC, blaisefonseca commented on app/views/forms/view/view-resource.directive.js
> +			$scope.updatedOrganizations = function(value)
unfortunately we will have to use the $watch here because when the user is editing the record and if he changes the organizations than this function which is only called on ng-init will not be called.

2021-02-09 21:13 UTC, blaisefonseca commented on app/views/forms/view/view-resource.directive.html
> +	<div class="record-body panel-body" ng-init="updatedOrganizations(document.organizations)">
will not work in case of edit -> view

2021-02-11 19:12 UTC, tahmeedshah commented on app/views/forms/edit/edit-resource-schema-base-directive.html
> +													schema="((schema_s:contact AND type_s:person))"
schema updated

2021-02-11 19:12 UTC, tahmeedshah commented on app/views/forms/edit/edit-resource-schema-base-directive.js
> +						$scope.displayBchRaSubjects = false;
used hasRiskAssessmentSubject

2021-02-11 19:13 UTC, tahmeedshah commented on app/views/forms/view/view-resource.directive.html
> +		<div ng-show="document.bchRaRecommend && document.bchRaRecommend != undefined && isBCH">
done as suggested

2021-02-11 19:13 UTC, tahmeedshah commented on app/views/forms/view/view-resource.directive.html
> +			<label>If “Risk assessment” was indicated as one of the “Thematic areas” in the previous question, please answer to the following question: would you like to recommend
label updated

2021-02-11 19:14 UTC, tahmeedshah commented on app/views/forms/view/view-resource.directive.html
> +				<div ng-if="document.bchRaRecommend">Yes</div>
done as suggested

2021-02-11 19:14 UTC, tahmeedshah commented on app/views/forms/view/view-resource.directive.html
> +				<label>Which section(s) of the “Guidance” this background material is relevant: </label>
done as suggested

2021-02-11 19:14 UTC, tahmeedshah commented on app/views/forms/view/view-resource.directive.html
> +				<ul ng-repeat="val in document.regions" class="list">
updated as suggested

2021-02-11 19:15 UTC, tahmeedshah commented on app/views/forms/view/view-resource.directive.js
> +			$scope.updatedOrganizations = function(value)
updated as suggested

2021-02-11 19:15 UTC, tahmeedshah commented on app/views/forms/view/view-resource.directive.html
> +	<div class="record-body panel-body" ng-init="updatedOrganizations(document.organizations)">
updated as suggested

2021-02-15 15:10 UTC, blaisefonseca requested changes
can you accept my two changes?

2021-02-15 15:10 UTC, blaisefonseca commented on app/views/forms/view/view-resource.directive.html
> +			<label>Would you like to recommend</label>
```suggestion
			<label>Would you like to recommend this document as background material for the “Guidance on Risk Assessment of Living Modified Organisms”?</label>
```

2021-02-15 15:10 UTC, blaisefonseca commented on app/views/forms/edit/edit-resource-schema-base-directive.html
> +														<div class="km-control-group" name="bchRaSubjects" required  caption="Please indicate to which section(s) of the “Guidance” this background material is relevant: ">
```suggestion
														<div class="km-control-group" name="bchRaSubjects" required  caption="Please indicate to which section(s) of the “Guidance” this background material is relevant">
```

2021-02-15 15:27 UTC, blaisefonseca approved these changes

2021-02-15 15:28 UTC, merged