Update document-selector
scbd/absch.cbd.int pull request #483
Opened 2021-03-01 17:33 UTC by tahmeedshah

2021-03-03 15:08 UTC, blaisefonseca requested changes
requires changes..

2021-03-03 15:08 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-biosafety-decision.directive.js
> +    app.directive("editBiosafetyDecision", "$controller", "thesaurusService", "$routeParams", "solr", 'editFormUtility', 'realm',
`[` was removed, this will break the app

2021-03-03 15:08 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-biosafety-decision.directive.js
> +                        fieldQueries: ['type_s: person'],
remove schemas and just use fieldQueries `schema_s:contact and type_s:person`

2021-03-04 10:18 UTC, tahmeedshah commented on app/views/forms/edit/abs/edit-abs-national-model-contractual-clause.html
> +                                               <div document-selector on-build-query="onBuildQuery(searchText, tab)" ng-model="document.relevantMeasures" question="measure" government="document.gover
government is no more required

2021-03-04 10:20 UTC, tahmeedshah commented on app/views/forms/edit/abs/edit-absCheckpointCommunique.html
> +                                                                  ng-model="document.entityWhoGrantedPIC" type="radio" skip-government="true" list-view="true"
skip-government="true" is no more required , have been removed

2021-03-04 10:20 UTC, tahmeedshah commented on app/views/forms/edit/abs/edit-absCheckpointCommunique.html
> +                                                                    ng-model="document.entityToWhomPICGranted" type="radio" skip-government="true" list-view="true"
removed

2021-03-04 10:20 UTC, tahmeedshah commented on app/views/forms/edit/abs/edit-absCheckpointCommunique.js
> +                    government: ["*"],
removed

2021-03-04 10:21 UTC, tahmeedshah commented on app/views/forms/edit/bch/directives/edit-biosafety-decision.directive.js
> +    app.directive("editBiosafetyDecision", "$controller", "thesaurusService", "$routeParams", "solr", 'editFormUtility', 'realm',
reverted

2021-03-04 10:21 UTC, tahmeedshah commented on app/views/forms/edit/bch/directives/edit-biosafety-decision.directive.js
> +                        fieldQueries: ['type_s: person'],
updated as suggested

2021-03-23 13:17 UTC, blaisefonseca commented on app/views/forms/edit/abs/edit-absCheckpoint.js
> +            iqueryOptions.government = $scope.document.government.identifier;
```suggestion
            queryOptions.government = $scope.document.government.identifier;
```

2021-03-23 13:26 UTC, blaisefonseca approved these changes

2021-03-23 13:26 UTC, merged