Small fixes
scbd/absch.cbd.int pull request #508
Opened 2021-05-19 20:37 UTC by tahmeedshah

fix autocomplete issue-DEVDESK-757
update CH name as per realmConfig- DEVDESK-759
enable the search option make lang optional when the add file type is image-DEVDESK-662

2021-05-21 11:31 UTC, blaisefonseca requested changes
can you delete this file?  app/img/help-images/DatetimeFull_control_gif.gif

2021-05-21 11:31 UTC, blaisefonseca commented on app/components/scbd-angularjs-controls/form-control-directives/km-form-languages.js
> +                        $scope.$broadcast('event:km-select-enable-search', {enabled:true, instanceId:$scope.instanceId});
this is not required. we need the search only when the user click on other languages where the list is big which already is enabling search.
```suggestion
                       
```

2021-05-21 11:31 UTC, blaisefonseca commented on app/components/scbd-angularjs-controls/form-control-directives/km-link.html
> +						<label class="control-label" ng-required="editor.visible && editor.isFile" for="Language">Language</label>
can we keep the control only make it optional

2021-05-21 11:31 UTC, blaisefonseca commented on app/components/scbd-angularjs-controls/form-control-directives/km-link.js
> +					$scope.editor.language = link.language||"";
why do you need default value?

2021-05-21 11:31 UTC, blaisefonseca commented on app/components/scbd-angularjs-controls/form-control-directives/km-link.js
> +				}
```suggestion
				function languageOptional(name){
				return ["audio/mpeg",
				        "audio/x-ms-wma",
				        "audio/x-wav",
				        "image/gif",
				        "image/jpeg",
				        "image/png",
				        "image/tiff",
				        "video/mpeg",
				        "video/mp4",
				        "video/quicktime",
				        "video/x-ms-wmv",
				        "video/x-msvideo",
				        "video/x-flv"].includes($scope.editor.mimeTypes)
				}
```

2021-05-21 11:31 UTC, blaisefonseca commented on app/components/scbd-angularjs-controls/form-control-directives/km-link.js
> +						if (extension != undefined && isImage(extension) ){
use regex as split  by . may not give good result if the file name is `xyz.avc.jpg` but it can be also done based on mime type, see the previous suggesion
```suggestion
						if (languageOptional() ){
```

2021-05-21 11:31 UTC, blaisefonseca commented on app/components/scbd-angularjs-controls/form-control-directives/km-link.js
> +								}
not sure why isFile is required. use languageOptional() fn

2021-05-21 17:21 UTC, tahmeedshah commented on app/components/scbd-angularjs-controls/form-control-directives/km-link.js
> +					$scope.editor.language = link.language||"";
For image if we don't select any language and then want to edit the same record in that case we need default value

2021-05-21 17:27 UTC, tahmeedshah commented on app/components/scbd-angularjs-controls/form-control-directives/km-link.js
> +								}
isFile is replaced with isShowAsterisk, 
it is using to show and hide * , i.e for optional language we hide *

2021-05-21 17:34 UTC, tahmeedshah commented
> DatetimeFull_control_gif.gif

DatetimeFull_control_gif.gif is actually the copy of already using Datetime_control_gif.gif.
we can replace DatetimeFull_control_gif.gif with new created gif file.
if we delete this we have to change all the HTML files where it is using.

2021-05-24 11:38 UTC, blaisefonseca commented on app/components/scbd-angularjs-controls/form-control-directives/km-link.js
> +					isShowAsterisk   :false,
use `isLanguageMandatory`

2021-05-24 12:17 UTC, blaisefonseca commented on app/components/scbd-angularjs-controls/form-control-directives/km-link.js
> +							mimeType  : link.mimeType
mimeType will be save in db, we do not want this to be saved

2021-05-24 12:21 UTC, blaisefonseca commented on app/views/shared/login-dialog.html
> +        <h3 class="color-green">For technical support please contact our help desk at: <span class="color-blue"><span style="text-transform: lowercase" ng-bind="chShortName"></span>@cbd.int</span></h
realm has email field

2021-05-24 12:31 UTC, blaisefonseca requested changes
small changes

2021-05-25 18:03 UTC, tahmeedshah commented on app/components/scbd-angularjs-controls/form-control-directives/km-link.js
> +							mimeType  : link.mimeType
in edit the mimeType is using to show language optional, in that case we will need mimeType from DB.

2021-05-28 17:35 UTC, blaisefonseca commented on app/components/scbd-angularjs-controls/form-control-directives/km-link.js
> +						"x-flv"];
```
"quicktime",
"x-ms-wmv",
"x-msvideo",
"x-flv"
```
 are not extension, can we just keep image ext for now. 
 ```
"gif",
"jpeg",
"png",
"tiff", 
"tif",
"jpg",
"jfif",
"bmp"
```

2021-05-28 17:42 UTC, blaisefonseca commented on app/components/scbd-angularjs-controls/form-control-directives/km-link.js
> +						var extension = $scope.editor.name.replace(/^.*\./, '');
`/\.(gif|jpe?g|tiff?|png|webp|bmp|png)$/i`

2021-06-04 16:59 UTC, blaisefonseca approved these changes

2021-06-04 17:03 UTC, merged