Update document selector
scbd/absch.cbd.int pull request #520
Opened 2021-06-13 19:32 UTC by tahmeedshah

2021-06-15 19:59 UTC, blaisefonseca requested changes
please maintain the existing contact schema query

2021-06-15 19:59 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-modified-organism.directive.js
> -						fieldQueries: ['schema_s:contact AND type_s:person'],
why `type_s:person` was removed?

2021-06-15 19:59 UTC, blaisefonseca commented on app/views/forms/edit/directives/edit-contact.directive.js
> +                    fieldQueries: ['schema_s:contact AND (refReferenceRecords_ss:* OR refNationalRecords_ss:*)'],
why type_s:organization was removed?

2021-06-16 05:10 UTC, tahmeedshah commented on app/views/forms/edit/bch/directives/edit-modified-organism.directive.js
> -						fieldQueries: ['schema_s:contact AND type_s:person'],
As per DEVDESK-798:
add below query for contacts
schema_s:contact AND (refReferenceRecords_ss:* OR refNationalRecords_ss:*)

2021-06-16 17:34 UTC, blaisefonseca commented on app/views/forms/edit/bch/directives/edit-modified-organism.directive.js
> -						fieldQueries: ['schema_s:contact AND type_s:person'],
it was an example, we need to keep existing query

2021-06-16 18:02 UTC, blaisefonseca approved these changes

2021-06-16 18:06 UTC, merged