update KB to use coverimages
scbd/absch.cbd.int pull request #840
Opened 2022-09-29 17:23 UTC by mattdias

update the cover images for announcements in KB
updated the style to use BS5 cards
removed inconsistent fonts and styles

2022-09-30 17:22 UTC, blaisefonseca commented on app/components/kb/articles-by-tag.vue
> -                        <ul class="article-with-tags-ul">
can you delete the css classes as well

2022-09-30 17:24 UTC, blaisefonseca commented on app/components/kb/filters.js
> +        format = 'DD MMM YYYY';
pass the required format from you usage instead of changing the global filter

2022-09-30 17:27 UTC, blaisefonseca commented on app/css/vue/kb/style.css
>  }
remove empty class

2022-09-30 17:27 UTC, blaisefonseca commented on app/css/vue/kb/style.css
> +
remove empty lines

2022-09-30 17:28 UTC, blaisefonseca commented on app/views/kb/home.vue
> -                            <div class="categerios-parahraph">
remove css class too

2022-09-30 17:29 UTC, blaisefonseca commented on app/components/kb/article-details.vue
> +                         <img v-bind:src="getSizedImage(article.coverImage.url, '800x800')" class="img-fluid">
it will be good to provide default image when cover image is not available

2022-09-30 17:30 UTC, blaisefonseca requested changes
see somments

2022-09-30 18:19 UTC, mattdias commented on app/components/kb/articles-by-tag.vue
> -                        <ul class="article-with-tags-ul">
i think it is still being used. In another PR i would get rid the whole KB style and use BS

2022-09-30 18:20 UTC, mattdias commented on app/components/kb/filters.js
> +        format = 'DD MMM YYYY';
we already have a function formatDateWithTime what we use in other places for time.

2022-09-30 18:21 UTC, mattdias commented on app/components/kb/popular-tags.vue
> +            </div>
Then they would show up in the KB homepage

2022-09-30 18:21 UTC, mattdias commented on app/css/vue/kb/style.css
>  }
done

2022-09-30 18:23 UTC, mattdias commented on app/css/vue/kb/style.css
> +
done

2022-09-30 18:25 UTC, mattdias commented on app/css/vue/kb/style.css
> +	padding: 10px;
any case we should eventually remove this whole style sheet

2022-09-30 18:26 UTC, mattdias commented on app/views/kb/home.vue
> -                            <div class="categerios-parahraph">
this was never a class

2022-09-30 18:27 UTC, mattdias commented on app/components/kb/article-details.vue
> +                         <img v-bind:src="getSizedImage(article.coverImage.url, '800x800')" class="img-fluid">
then we will have to have an image even if we dont want one. what should the default image be?

2022-10-14 15:19 UTC, blaisefonseca commented on app/components/kb/filters.js
> +        format = 'DD MMM YYYY';
`formatDateWithTime` is in angularjs portion, this one is in vueJs

2022-10-14 15:21 UTC, blaisefonseca commented on app/components/kb/popular-tags.vue
> +            </div>
push them from Javascript, what difference will it make if they show up on KB homepage?

2022-10-14 15:28 UTC, blaisefonseca commented on app/components/kb/article-details.vue
> +                         <img v-bind:src="getSizedImage(article.coverImage.url, '800x800')" class="img-fluid">
generally simple div with light color or any blank image.

2022-10-14 17:53 UTC, mattdias commented on app/components/kb/popular-tags.vue
> +            </div>
it doesn't follow the same format on the homepage. announcements change so would need to get latest announcements dynamically.

2022-10-17 15:44 UTC, mattdias commented on app/components/kb/filters.js
> +        format = 'DD MMM YYYY';
ok

2022-10-17 16:51 UTC, mattdias commented on app/components/kb/article-details.vue
> +                         <img v-bind:src="getSizedImage(article.coverImage.url, '800x800')" class="img-fluid">
I dont think we need one.

2022-10-18 18:28 UTC, mattdias commented on app/components/kb/articles-by-tag.vue
> -                        <ul class="article-with-tags-ul">
removed kb style from the KB.

2022-10-18 18:35 UTC, mattdias commented
added random shuffle to the relevant articles so not always the same. 
fixed the back button, since we don't always come from KB home page
remove links to the custom KB style sheet, replaced with bootstrap.
added dates.

2022-10-19 21:35 UTC, blaisefonseca commented on app/components/kb/relevant-articles.vue
> +            return array;
`return array.map((item, i)=>{ return { ...item, randomSort : Math.floor(Math.random() * 100)}}).sort((a,b)=> a.randomSort-b. randomSort)` is simple to understand

eg `[{name:'blaise'}, {name:'fonse'}, {name:'name'}].map((item, i)=>{ return { ...item, randomSort : Math.floor(Math.random() * 100)}}).sort((a,b)=> a.randomSort-b. randomSort)`

2022-10-19 21:38 UTC, blaisefonseca commented on app/components/kb/article-details.vue
> +            window.history.back();
if they come from external site like google, they will go back to google.

2022-10-19 21:42 UTC, blaisefonseca commented on app/components/kb/relevant-articles.vue
> +        <h4 v-if="!hideTitle">
why hide the title?

if you need to override some section use slots https://vuejs.org/guide/components/slots.html#slot-content-and-outlet

2022-10-19 21:44 UTC, blaisefonseca reviewed
two more comments, can you in future not add new feature code to existing PR which is under review, difficult to track

2022-10-20 14:00 UTC, mattdias commented on app/components/kb/relevant-articles.vue
> +            return array;
ok

2022-10-20 14:01 UTC, mattdias commented on app/components/kb/article-details.vue
> +            window.history.back();
but that is better than going back the wrong page.

2022-10-20 14:18 UTC, mattdias commented on app/components/kb/relevant-articles.vue
> +        <h4 v-if="!hideTitle">
im not sure what you mean. 
relevantarticles is used in side bar and has a title, but now I am  also using it on categories page when displaying latest announcements to look the same layout as the other categories data from the json

2022-10-20 18:07 UTC, merged