add NR5 schema details in realm-conf file
scbd/absch.cbd.int pull request #888
Opened 2023-05-10 18:09 UTC by tahmeedshah

### General description
added NR5 schema details in realm-config file

### Designs
_Link to the related design prototypes (if applicable)_

### Testing instructions
_Provide minimal instructions on how to test this PR._

* Apart from the added feature / bug fix, check overall performance, styling...

## Checklist before merging
* [ ]  Branch name / PR includes the related Jira ticket Id.
* [ ]  Tests to check core implementation / bug fix added.
* [ ]  All checks in Continuous Integration workflow pass.
* [ ]  Feature functionally tested by reviewer(s).
* [ ]  Code reviewed by reviewer(s).
* [ ]  Documentation updated (README, CHANGELOG...) (if required)

2023-05-10 20:14 UTC, blaisefonseca commented on app/app-data/bch/realm-configuration.json
> +             "es" : "Cuarto informe nacional sobre la aplicación del Protocolo de Cartagena sobre Seguridad de la Biotecnología",
replace fourth with Fifth in all 5 languages
![image](https://github.com/scbd/absch.cbd.int/assets/7049230/f112d6e9-c4d6-4ef5-8faf-03131958514a)

2023-05-10 20:15 UTC, blaisefonseca requested changes
replace fourth with fifth

2023-05-11 05:20 UTC, tahmeedshah commented on app/app-data/bch/realm-configuration.json
> +             "es" : "Cuarto informe nacional sobre la aplicación del Protocolo de Cartagena sobre Seguridad de la Biotecnología",
replaced "fourth" with "fifth" in all 5 languages but not sure about the Chinese language.
 
![chinese-text](https://github.com/scbd/absch.cbd.int/assets/58165529/990514e8-aebc-40cd-a68c-6d0656b3ae1e)

2023-05-15 18:04 UTC, blaisefonseca approved these changes

2023-05-15 18:04 UTC, merged