tahmeed/CHM-72-ABS-NR1-Part-III
scbd/absch.cbd.int pull request #920
Opened 2023-05-25 05:35 UTC by tahmeedshah

### General description
ABS-NR1-Part-III copy text to translation file
ABS-NR1-Part-III questions structure

### Designs
_Link to the related design prototypes (if applicable)_

### Testing instructions
_Provide minimal instructions on how to test this PR._

* Apart from the added feature / bug fix, check overall performance, styling...

## Checklist before merging
* [ ]  Branch name / PR includes the related Jira ticket Id.
* [ ]  Tests to check core implementation / bug fix added.
* [ ]  All checks in Continuous Integration workflow pass.
* [ ]  Feature functionally tested by reviewer(s).
* [ ]  Code reviewed by reviewer(s).
* [ ]  Documentation updated (README, CHANGELOG...) (if required)

2023-05-30 15:20 UTC, blaisefonseca commented on app/app-data/abs/report-analyzer/npNationalReport1.js
> +                  "value": "60CD889F-4E08-450C-A67C-5F29A2B1E704",
can we use true and true.some like bch

2023-05-30 15:30 UTC, blaisefonseca requested changes
see comments

2023-05-30 15:30 UTC, blaisefonseca commented on app/app-data/abs/report-analyzer/npNationalReport1.js
> +         },
![image](https://github.com/scbd/absch.cbd.int/assets/7049230/b64c756a-ab54-414a-9e82-f7528dfbd60f)
is missing

2023-05-30 15:30 UTC, blaisefonseca commented on app/app-data/abs/report-analyzer/npNationalReport1.js
> +                  "title": nr1T.yesInAllCases
` "type": "lstring",
                  "caption": nr1T.pleaseExplainYourResponse` is missing for Yes

2023-05-30 15:45 UTC, tahmeedshah commented on app/app-data/abs/report-analyzer/npNationalReport1.js
> +                  "title": nr1T.yesInAllCases
![image](https://github.com/scbd/absch.cbd.int/assets/58165529/a187deb4-2394-4305-b720-52c3b27b8d26)

2023-06-01 14:07 UTC, blaisefonseca approved these changes

2023-06-01 14:07 UTC, merged