Tahmeed/ABS NR1 previous answers mapping
scbd/absch.cbd.int pull request #958
Opened 2023-06-24 10:35 UTC by tahmeedshah

### General description

Create NR1 and Interim National Reports mapping file

add loadPreviousReport at NR1 edit fom

### Designs
_Link to the related design prototypes (if applicable)_

### Testing instructions
_Provide minimal instructions on how to test this PR._

* Apart from the added feature / bug fix, check overall performance, styling...

## Checklist before merging
* [ ]  Branch name / PR includes the related Jira ticket Id.
* [ ]  Tests to check core implementation / bug fix added.
* [ ]  All checks in Continuous Integration workflow pass.
* [ ]  Feature functionally tested by reviewer(s).
* [ ]  Code reviewed by reviewer(s).
* [ ]  Documentation updated (README, CHANGELOG...) (if required)

2023-06-27 14:40 UTC, blaisefonseca requested changes
fix schema name

2023-06-27 14:40 UTC, blaisefonseca commented on app/views/forms/edit/abs/edit-national-report-1.js
> +                        schema: 'npInterimNationalReport1',
wrong schema name

2023-07-03 08:24 UTC, tahmeedshah commented on app/views/forms/edit/abs/edit-national-report-1.js
> +                        schema: 'npInterimNationalReport1',
the same was used at app\app-data\report-analyzer-mapping.js ,  "type": "npInterimNationalReport1"

2023-07-04 15:22 UTC, blaisefonseca approved these changes

2023-07-04 15:37 UTC, merged